/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-23 06:06:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.myCR;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.go.cris.ptl.mng.menu.vo.MngMenuVo;

public final class myClRsrch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/jquery.treeview.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/code.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar longinInfo = 'devsuper';\r\n");
      out.write("\r\n");
      out.write("\tparam = {};\r\n");
      out.write("\tparam.userId = longinInfo;\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: ctxt + '/board/myClinicalResearch/registration_mng.do',\r\n");
      out.write("\t\tdata : param,\r\n");
      out.write("\t\ttype:'POST',\r\n");
      out.write("\t\tasync:false,\r\n");
      out.write("\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar resArr = [];\r\n");
      out.write("\t\t\tvar html =\"\";\r\n");
      out.write("\t\t\tfor(var i=0; i<res.length;i++){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar hideRows = res.length -3\r\n");
      out.write("\t\t\t\tresArr=res[i];\r\n");
      out.write("\t\t\t\thtml+='<tr class=\"thtr\" style=\"display:\\'\\'\">';\r\n");
      out.write("\t\t\t\t\thtml+='<th>등록번호</th>';\r\n");
      out.write("\t\t\t\t\thtml+='<td colspan=\"3\">'+resArr.SYSTEM_NUMBER+'</td>';\r\n");
      out.write("\t\t\t\t\thtml+='<th>상태</th>';\r\n");
      out.write("\t\t\t\t\thtml+='<td>'+resArr.STATUS+'</td>';\r\n");
      out.write("\t\t\t\thtml+='</tr>';\r\n");
      out.write("\t\t\t\thtml+='<tr class=\"thtr\">';\r\n");
      out.write("\t\t\t\t\thtml+='<th>연구제목<th>';\r\n");
      out.write("\t\t\t\t\thtml+='<td colspan=\"5\">'+resArr.RESEARCH_TITLE_KR+'</td>';\r\n");
      out.write("\t\t\t\thtml+='</tr>';\r\n");
      out.write("\t\t\t\thtml+='<tr class=\"thtr\">';\r\n");
      out.write("\t\t\t\t\thtml+='<th>최초제출일</th>';\r\n");
      out.write("\t\t\t\t\thtml+='<td>'+resArr.INS_DATE+'</td>';\r\n");
      out.write("\t\t\t\t\thtml+='<th>검토/승인일</th>';\r\n");
      out.write("\t\t\t\t\thtml+='<td>'+resArr.APP_DATE+'/'+resArr.LAST_DATE+'</td>';\r\n");
      out.write("\t\t\t\t\thtml+='<th>최종갱신일</th>';\r\n");
      out.write("\t\t\t\t\thtml+='<td>'+resArr.UPT_DATE+'</td>';\r\n");
      out.write("\t\t\t\thtml+='</tr>';\r\n");
      out.write("\t\t\t\thtml+='<tr colspan=\"6\">';\r\n");
      out.write("\t\t\t\t\thtml +='<td></td>';\r\n");
      out.write("\t\t\t\t\thtml += '<td><input type=\"button\" name=\"\" value=\"제출 이력\"></td>';\r\n");
      out.write("\t\t\t\t\thtml += '<td><input type=\"button\" name=\"\" value=\"연구 정보\"></td>';\r\n");
      out.write("\t\t\t\t\thtml += '<td><input type=\"button\" name=\"\" value=\"연구 결과\"></td>';\r\n");
      out.write("\t\t\t\t\thtml += '<td><input type=\"button\" name=\"\" value=\"삭제\"></td>';\r\n");
      out.write("\t\t\t\t\thtml += '<td><input type=\"button\" name=\"\" value=\"관리자 변경\"></td>';\r\n");
      out.write("\t\t\t\thtml+='</tr>';\r\n");
      out.write("\t\t\t\t/* html+='<tr>';\r\n");
      out.write("\t\t\t\t\thtml += '<td> 등록관리자 지정 연구 '+hideRows+'개 더 보기</td>';\r\n");
      out.write("\t\t\t\thtml+='</tr>'; */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#tbodyData').html(html);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})  //  end of the first ajax\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log($('#tbodyData').parents('tr').eq(0))\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\" style=\"min-height: 600px;\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"divRefreshArea\">\r\n");
      out.write("\t\t\t<h3 style=\"margin-left: 10%;\">my 임상 연구</h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"\" name=\"etl_form\">\r\n");
      out.write("\t     \t<table id=\"example0\" class=\"tbl_type\"  style=\"width:55%;margin-left: 10%;\"> \r\n");
      out.write("\t        \t<colgroup>\r\n");
      out.write("\t        \t\t<col style=\"width:10%;\"/>\r\n");
      out.write("\t        \t\t<col style=\"width:10%;\"/>\r\n");
      out.write("\t        \t\t<col style=\"width:10%;\"/>\r\n");
      out.write("\t        \t\t<col style=\"width:8%;\"/>\r\n");
      out.write("\t        \t\t<col style=\"width:10%;\"/>\r\n");
      out.write("\t        \t\t<col style=\"width:10%;\"/>\r\n");
      out.write("\t           </colgroup> \r\n");
      out.write("\t\t           <thead>    \r\n");
      out.write("\t\t         \t<tr>\r\n");
      out.write("\t\t         \t\t<th colspan=\"6\" style=\"text-align: left;;\">등록 관리자</th>\r\n");
      out.write("\t\t        \t </tr>        \r\n");
      out.write("\t\t       \t</thead>\r\n");
      out.write("\t\t       \t<tbody id=\"tbodyData\" >       \r\n");
      out.write("\t\t        </tbody>\t\t        \r\n");
      out.write("\t     \t</table>\t\t\r\n");
      out.write("     \t</form>\r\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
