/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-27 08:03:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.myCR;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regSubmission_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2 style=\"margin-left: 5%;\">연구상태에 대한 기록 변경 정보</h2>\r\n");
      out.write("\t<div id=\"clinicalRsTitle\" style=\"margin-left: 5%;\"></div></br>\r\n");
      out.write("\t<div id=\"tableNone\"></div>\r\n");
      out.write("\t<table style=\"width:55%;margin-left: 5%;\">\r\n");
      out.write("\t<colgroup>\r\n");
      out.write("        <col style=\"width:5%\" />\r\n");
      out.write("        <col style=\"width:5%\" />\r\n");
      out.write("        <col style=\"width:5%\">\r\n");
      out.write("        <col style=\"width:20%\">\r\n");
      out.write("        <col style=\"width:20%\">\r\n");
      out.write("      </colgroup>\r\n");
      out.write("\t\t<thead id=\"theadData\">\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody id=\"tbodyData\">\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type=\"button\" id=\"popCloseBtn\" name=\"popCloseBtn\" value=\"닫기\">\r\n");
      out.write("</body>\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar idx = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar separator = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${separator}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar title = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar url = $(location).attr('href');\r\n");
      out.write("\tvar baseUrl = url.substr(0,url.lastIndexOf(\"/\"));\r\n");
      out.write("\t\r\n");
      out.write("\tvar params = {};\r\n");
      out.write("\tparams.seq = idx;\r\n");
      out.write("\tparams.separator = separator;\r\n");
      out.write("\t\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#clinicalRsTitle').html(title);\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:  baseUrl+\"/regSubData.do\",\r\n");
      out.write("\t\tdata : params,\r\n");
      out.write("\t\ttype:'POST',\r\n");
      out.write("\t\tsuccess:function(res){\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tvar idx = res.length;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(idx)\r\n");
      out.write("\t\t\tif(idx!=0){\r\n");
      out.write("\t\t\t\tvar theadHtml = \"\";\r\n");
      out.write("\t\t\t\ttheadHtml = '<tr><th>최신순</th><th style=\"text-aligh:center;\">변경 전</th><th style=\"text-aligh:center;\">변경 후</th><th style=\"text-aligh:center;\">변경 일시</th><th style=\"text-aligh:center;\">변경 사유</th></tr>';\r\n");
      out.write("\t\t\t\t$('#theadData').html(theadHtml);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i=0 ; i < res.length ; i++) {\r\n");
      out.write("\t\t\t\t\tvar tdRwSpn = '<td style=\"word-break:break-all;text-align:center;\">';\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += '<tr>';\r\n");
      out.write("\t\t\t\t\thtml +=  tdRwSpn\r\n");
      out.write("\t\t\t\t\t\thtml += idx--;\r\n");
      out.write("\t\t\t\t\thtml += '</td>';\r\n");
      out.write("\t\t\t\t\thtml +=  tdRwSpn\r\n");
      out.write("\t\t\t\t\t\thtml += res[i].LAST_STAT_AL;\r\n");
      out.write("\t\t\t\t\thtml += '</td>';\r\n");
      out.write("\t\t\t\t\thtml += tdRwSpn;\r\n");
      out.write("\t\t\t\t\t\thtml += res[i].CHANGE_STAT_AL;\r\n");
      out.write("\t\t\t\t\thtml += '</td>';\r\n");
      out.write("\t\t\t\t\thtml +=  '<td style=\"word-break:break-all;padding-left:20px\">';\r\n");
      out.write("\t\t\t\t\t\thtml += fn_changeDate(res[i]);\r\n");
      out.write("\t\t\t\t\thtml += '</td>';\r\n");
      out.write("\t\t\t\t\tif(\"반려\"==res[i].CHANGE_STAT_AL){\r\n");
      out.write("\t\t\t\t\t\thtml += '<td style=\"word-break:break-all;padding-left:20px\">';\r\n");
      out.write("\t\t\t\t\t\thtml += res[i].CODE_NAME +\" : \"+res[i].STAT_REASON_ETC;\r\n");
      out.write("\t\t\t\t\t\thtml += '</td>';\r\n");
      out.write("\t\t\t\t\t} else {  html +=tdRwSpn;   }\r\n");
      out.write("\t\t\t\t\thtml += '</tr>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t$('#tbodyData').html(html);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\thtml += \"변경 이력이 없습니다. \";\r\n");
      out.write("\t\t\t\t$('#tableNone').html(html);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})  //  end of ajax\r\n");
      out.write("\t\r\n");
      out.write("\t$('#popCloseBtn').click(function(){\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t});  //  end of popCloseBtn\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function fn_changeDate(resForIdx, tdRwSpn){\r\n");
      out.write("\tvar html = \"\";\r\n");
      out.write("\tif(\"제출\" == resForIdx.CHANGE_STAT_AL){\r\n");
      out.write("\t\tif(resForIdx.CHARGE_DATE  != \"\" && resForIdx.CHARGE_DATE  != null){\r\n");
      out.write("\t\t\thtml += \"등록자 : \" + resForIdx.CHANGE_DATE_AL +\"<br>\";\r\n");
      out.write("\t\t\thtml += \"* 책임자 : \" + resForIdx.CHARGE_DATE;\r\n");
      out.write("\t\t\t\tif(resForIdx.CHARGE_CANCEL ==\"Y\") html += \", 취소\";\r\n");
      out.write("\t\t\t\telse html += \", 확인\";\r\n");
      out.write("\t\t\thtml += \"<br>\";\r\n");
      out.write("\t\t\thtml += \"* 실무자 : \" + resForIdx.WORK_DATE;\r\n");
      out.write("\t\t\t\tif(resForIdx.WORK_CANCEL ==\"Y\") html += \", 취소\";\r\n");
      out.write("\t\t\t\telse html += \", 확인\";\r\n");
      out.write("\t\t\thtml += \"<br>\";\r\n");
      out.write("\t\t} \r\n");
      out.write("\t} else {\r\n");
      out.write("\t\thtml += \"등록자 : \" + resForIdx.CHANGE_DATE_AL;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn html;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
