/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-11 00:30:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.write;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cris_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\n");
      out.write("*{margin:0px; padding:0px;}\r\n");
      out.write("\r\n");
      out.write("#navigation{\r\n");
      out.write("\tposition:fixed; \r\n");
      out.write("\ttop:0px;\r\n");
      out.write("\tleft:0px;\r\n");
      out.write("\theight:80px;\r\n");
      out.write("\twidth:100%; \r\n");
      out.write("\tbackground:#000;\t  \r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-size:14px;\r\n");
      out.write("}\r\n");
      out.write("#navigation ul { list-style:none; margin-top:150px; }\t\t   \t\t\r\n");
      out.write("#navigation li { display:inline; margin-right:10px; }\r\n");
      out.write("#navigation li a { text-decoration:none; color:black;}\r\n");
      out.write("#navigation li a:hover {color:#0F0;}\r\n");
      out.write("\r\n");
      out.write("#wrap { width:100%;margin:0 auto;margin-top:80px; }\r\n");
      out.write("\r\n");
      out.write("#step1{background:white; height:1200px;}\r\n");
      out.write("#step2{background:RoyalBlue; height:1200px;}\r\n");
      out.write("#step3{background:Gold; height:1200px;}\r\n");
      out.write("#step4{background:RoyalBlue; height:1200px;}\n");
      out.write("#step5{background:white; height:1200px;}\n");
      out.write("#step6{background:RoyalBlue; height:1200px;}\n");
      out.write("#step7{background:white; height:1200px;}\n");
      out.write("#step8{background:RoyalBlue; height:1200px;}\n");
      out.write("#step9{background:white; height:1200px;}\n");
      out.write("#step10{background:RoyalBlue; height:1200px;}\n");
      out.write("#step11{background:white; height:1200px;}\n");
      out.write("#step12{background:RoyalBlue; height:1200px;}\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar cur_scoll=1;\n");
      out.write("\tvar old_scoll=1;\n");
      out.write("\tvar speed = 300;\t// 스크롤 스피드 수치로 사용할 변수 \r\n");
      out.write("\tvar cur_top =0;\r\n");
      out.write("\tvar scroll_event = true;\r\n");
      out.write("\tvar page_height = 1200;\r\n");
      out.write("\t//로직\r\n");
      out.write("\tfunction scrolling(obj){\r\n");
      out.write("\t\tif (!obj){\t// 예외처리, 현재는 기능적으로 필요한 부분은 아님, 관례적 사용\r\n");
      out.write("\t\t\t$('html, body').animate({scrollTop:0},speed);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar posTop = $(obj).offset().top -80;\t// posTop = 매개변수로 들어온 컨텐츠 obj 의 offset().top - 네비게이션 높이\r\n");
      out.write("\t\t\t$('html, body').animate({scrollTop:posTop}, speed )\t// body의 스크롤이동 : posTop\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#step1\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step2\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step3\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step4\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step5\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step6\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step7\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step8\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step9\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step10\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step11\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\t\t$(\"#step12\").load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/write/step/step1.do\");\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"ul li a\").click(function(){\t// 네비게이션 클릭시\r\n");
      out.write("\t\t\tvar direction = $(this).attr(\"href\");\t// direction = 클릭한 요소의 href 속성\r\n");
      out.write("\t\t\tcur_scoll = Number(direction.replace('#step',''));\r\n");
      out.write("\t\t\tscrolling( direction );\t// direction 을 인자로 함수 실행\r\n");
      out.write("\t\t\tcur_top = $(window).scrollTop();\r\n");
      out.write("\t\t\treturn false;\t// 본래 이벤트 방지    \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("  \t\t$(document).on('mousewheel ',function(e) {\r\n");
      out.write("\t\t\tcur_top = $(window).scrollTop();\r\n");
      out.write("\t\t\tvar cur_add = cur_top % page_height;\r\n");
      out.write("\t\t\tif(cur_top >= page_height){\r\n");
      out.write("\t\t\t\tcur_scoll = Math.round(cur_top / page_height) ;\r\n");
      out.write("\t\t\t\tif(cur_add > 1000){\r\n");
      out.write("\t\t\t\t\tcur_scoll = cur_scoll +1;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(Number(cur_scoll) > 12){  \r\n");
      out.write("\t\t\t\t\tcur_scoll = 12;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tcur_scoll=1;\r\n");
      out.write("\t\t\t}   \r\n");
      out.write("\t\t});  \r\n");
      out.write("  \t\t\r\n");
      out.write("\t\t$(document).keyup(function(e){\r\n");
      out.write("\t\t\tif(e.keyCode ==38){\r\n");
      out.write("\t\t\t\tif(cur_scoll != 1){\r\n");
      out.write("\t\t\t\t\tcur_scoll = Number(cur_scoll) -1;\t\r\n");
      out.write("\t\t\t\t\t$(\"#nav\"+cur_scoll).trigger('click');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else if(e.keyCode ==40){\r\n");
      out.write("\t\t\t\tcur_scoll = Number(cur_scoll) + 1;   \r\n");
      out.write("\t\t\t\tif(Number(cur_scoll) > 12){\r\n");
      out.write("\t\t\t\t\tcur_scoll = 12;\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#nav\"+cur_scoll).trigger('click');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fn_setScroll(){\r\n");
      out.write("\t\tcur_top = $(window).scrollTop();\r\n");
      out.write("\t\tvar cur_add = cur_top % page_height;\r\n");
      out.write("\t\tif(cur_top >= page_height){\r\n");
      out.write("\t\t\tcur_scoll = Math.round(cur_top / page_height) ;\r\n");
      out.write("\t\t\tif(cur_add > 1000){\r\n");
      out.write("\t\t\t\tcur_scoll = cur_scoll +1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(Number(cur_scoll) > 12){  \r\n");
      out.write("\t\t\t\tcur_scoll = 12;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tcur_scoll=1;\r\n");
      out.write("\t\t}  \r\n");
      out.write("\t}\r\n");
      out.write("\t\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("<div id=\"navigation\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"#step1\" id=\"nav1\"> SALMON </a></li>\r\n");
      out.write("        <li><a href=\"#step2\" id=\"nav2\"> ROYALBLUE </a> </li>    \r\n");
      out.write("        <li><a href=\"#step3\" id=\"nav3\"> GOLD </a> </li>\r\n");
      out.write("        <li><a href=\"#step4\" id=\"nav4\"> BLACK </a> </li>\r\n");
      out.write("        <li><a href=\"#step5\" id=\"nav5\"> SALMON </a> </li>\r\n");
      out.write("        <li><a href=\"#step6\" id=\"nav6\"> ROYALBLUE </a> </li>\r\n");
      out.write("        <li><a href=\"#step7\" id=\"nav7\"> GOLD </a> </li>\r\n");
      out.write("        <li><a href=\"#step8\" id=\"nav8\"> BLACK </a> </li>\r\n");
      out.write("        <li><a href=\"#step9\" id=\"nav9\"> SALMON </a> </li>\r\n");
      out.write("        <li><a href=\"#step10\" id=\"nav10\"> ROYALBLUE </a> </li>\r\n");
      out.write("        <li><a href=\"#step11\" id=\"nav11\"> GOLD </a> </li>\r\n");
      out.write("        <li><a href=\"#step12\" id=\"nav12\"> BLACK </a> </li>  \r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\" onclick=\"fn_setScroll();\">\r\n");
      out.write("    <div id=\"step1\"></div>\r\n");
      out.write("    <div id=\"step2\"></div>\r\n");
      out.write("    <div id=\"step3\"></div>\r\n");
      out.write("    <div id=\"step4\"></div>  \r\n");
      out.write("    <div id=\"step5\"></div>  \r\n");
      out.write("    <div id=\"step6\"></div>  \r\n");
      out.write("    <div id=\"step7\"></div>\r\n");
      out.write("    <div id=\"step8\"></div>\r\n");
      out.write("    <div id=\"step9\"></div>\r\n");
      out.write("    <div id=\"step10\"></div>\r\n");
      out.write("    <div id=\"step11\"></div>\r\n");
      out.write("    <div id=\"step12\"></div> \r\n");
      out.write("</div>   \r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
