/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-19 05:14:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.go.cris.commons.constants.Constants;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<style>\r\n");
      out.write("/*로그인*/\r\n");
      out.write("#content{\r\n");
      out.write("\theight:750px;\r\n");
      out.write("}\r\n");
      out.write(".loginContents { \r\n");
      out.write("\twidth: 100%; \r\n");
      out.write("\tmax-width: 340px; \r\n");
      out.write("\theight: auto;  \r\n");
      out.write("\tmargin:0 auto; \r\n");
      out.write("\tmargin-top:10%; \r\n");
      out.write("\tbackground: #fff; \r\n");
      out.write("\tborder:1px solid #cdd3d9; \r\n");
      out.write("\tpadding: 50px;\r\n");
      out.write("} \r\n");
      out.write("/* .login_ad { float: left;  width: 620px; height: 365px; margin: 40px 0; background: #fff; border:1px solid #cdd3d9; padding: 30px; }\r\n");
      out.write(" */\r\n");
      out.write(".loginContainer{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("}\r\n");
      out.write(".loginContainer #form { \r\n");
      out.write("\tmargin: 40px 0 0; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginContainer .loginInput { \r\n");
      out.write("\tpadding: 10px; \r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tmax-width: 320px; \r\n");
      out.write("\theight: 30px; \r\n");
      out.write("\tbackground: #efefef; \r\n");
      out.write("\tmargin: 0 0 10px; \r\n");
      out.write("\tposition:relative; \r\n");
      out.write("}\r\n");
      out.write(".loginContainer .loginInput label { \r\n");
      out.write("\tposition:absolute; \r\n");
      out.write("\twidth: 40px; \r\n");
      out.write("\theight: 30px; \r\n");
      out.write("\tline-height: 30px; \r\n");
      out.write("\ttext-align: center; \r\n");
      out.write("\tvertical-align: middle; \r\n");
      out.write("}\r\n");
      out.write(".loginContainer .loginInput label img { width: 20px; vertical-align: middle; }\r\n");
      out.write(".loginContainer .loginInput input {\r\n");
      out.write("\t height: 30px; \r\n");
      out.write("\t border: 0 !important; \r\n");
      out.write("\t width: 85%; \r\n");
      out.write("\t background: none; \r\n");
      out.write("\t font-size: 14px; \r\n");
      out.write("\t line-height: 30px; \r\n");
      out.write("\t /*font-weight: 600;*/ \r\n");
      out.write("\t letter-spacing: 0.03em; \r\n");
      out.write("\t color: #333; \r\n");
      out.write("\t margin-left:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(".loginContainer label.idCheck { display: inline-block; width: 120px; height: 18px; line-height: 18px; font-size: 13px;  letter-spacing: -0.03em;  }\r\n");
      out.write(".loginContainer label input[type=checkbox] { display: inline-block; width:13px; height: 13px; background: none; border:1px solid #dcdcdc; margin: 0 7px 0 0; vertical-align: center; }\r\n");
      out.write(".loginContainer .register { display: inline-block;  width: 215px; text-align: right; line-height: 18px; font-size: 13px; margin: 4px 0 0; }\r\n");
      out.write(".loginContainer .register a { font-weight: 600; color: #333; font-size: 15px; padding-left: 5px; }\r\n");
      out.write(".loginContainer .register a:hover { color: #2ab3ed; transition: 0.3s; }\r\n");
      out.write("\r\n");
      out.write(".loginContainer .loginBtn { \r\n");
      out.write("\tdisplay: block; \r\n");
      out.write("\tmargin: 25px 0 15px; \r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmax-width:340px; \r\n");
      out.write("\theight: 50px; \r\n");
      out.write("\tborder: 0; \r\n");
      out.write("\tcursor: pointer;  \r\n");
      out.write("\tletter-spacing: 0.5em;\r\n");
      out.write("\tfont-size: 18px; \r\n");
      out.write("\tfont-weight: 600; \r\n");
      out.write("\tcolor: #fff; \r\n");
      out.write("\tbackground: #2ab3ed url('../img/common/tab_ptn.gif'); \r\n");
      out.write("}\r\n");
      out.write(".loginContainer .loginBtn:hover { background: #393939; transition: 1s; }\r\n");
      out.write(".loginContainer .findPW { display: block; text-align: center; font-size: 13px; line-height: 20px; text-decoration: underline; font-style: italic;  color: #aaa; }\r\n");
      out.write(".loginContainer .findPW:hover { color: #393939; }\r\n");
      out.write(".loginFail {text-align: center; margin-top: 35px; color: red}\r\n");
      out.write("@media all and (max-width:620px) {\r\n");
      out.write("\t.loginContents{\r\n");
      out.write("\t\tmargin-top:80px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("@media all and (max-width:515px) {\r\n");
      out.write("\t.loginContents{\r\n");
      out.write("\t\tmargin-top:50px;\r\n");
      out.write("\t\tpadding:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginContainer #form {\r\n");
      out.write("\t    margin: 30px 0 0;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 502px){\r\n");
      out.write("\t .loginContainer .findPW{\r\n");
      out.write("\t\tdisplay:none;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("@media all and (max-width:460px) {\r\n");
      out.write("\t.loginContents{\r\n");
      out.write("\t\tmax-width: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginContainer .loginInput{\r\n");
      out.write("\t\tmax-width: 280px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginContainer label.idCheck {\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height: 18px;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.loginContainer #form {\r\n");
      out.write("\t    margin: 20px 0 0;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("@media all and (max-width:400px) {\r\n");
      out.write("\t.loginContents{\r\n");
      out.write("\t\tmax-width: 260px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginContainer .loginInput{\r\n");
      out.write("\t\tmax-width: 240px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("@media all and (max-width:340px) {\r\n");
      out.write("\t.loginContents{\r\n");
      out.write("\t\tmax-width: 220px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginContainer .loginInput{\r\n");
      out.write("\t\tmax-width: 200px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>로그인 | 국립의과학지식센터</title>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/js/rsa/jsbn.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/js/rsa/rsa.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/js/rsa/prng4.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/js/rsa/rng.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(function() {\r\n");
      out.write("     $(\".loginInput input\").focus(function() {\r\n");
      out.write("      }).blur(function() {\r\n");
      out.write("        if($(this).val()==\"\") $(this).prev(\".tag\").show();\r\n");
      out.write("      });\r\n");
      out.write("      if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' == 'false'){\r\n");
      out.write("        $(\"#loginid\").focus();\r\n");
      out.write("        $(\"#loginid\").val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("        \r\n");
      out.write("        $(\".loginFail\").html('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("        \r\n");
      out.write("      }else if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' == 'true'){\r\n");
      out.write("        location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/';\r\n");
      out.write("      }else{    \t  \r\n");
      out.write("        var form = document.form;\r\n");
      out.write("        \r\n");
      out.write("        $(\"#loginid\").focus();\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function fncLogin(){\r\n");
      out.write("      var form = document.form;\r\n");
      out.write("\r\n");
      out.write("      if ($(\"#loginid\").val() == '') {\r\n");
      out.write("        fn_alert('아이디를 입력하세요','c');\r\n");
      out.write("        $(\"#loginid\").focus();\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      if($(\"#password\").val() == \"\"){\r\n");
      out.write("         fn_alert(\"비밀번호를 입력 하세요\",'c');\r\n");
      out.write("         $(\"#password\").focus();\r\n");
      out.write("         return;\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write("              var frmObj = $('<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login/loginProcess.do\" method=\"post\"></form>');\r\n");
      out.write("          \r\n");
      out.write("\t           frmObj.append('<input type=\"hidden\" name=\"loginid\" value=\"' + $('#loginid').val() + '\"/>');\r\n");
      out.write("\t           frmObj.append('<input type=\"hidden\" name=\"password\" value=\"' + $('#password').val() + '\"/>');\r\n");
      out.write("\t\t\t\r\n");
      out.write("              frmObj.append('<input type=\"hidden\" name=\"returnURL\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.returnURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>');\r\n");
      out.write("              frmObj.append('<input type=\"hidden\" name=\"returnUrl\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${returnURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/></form>');\r\n");
      out.write("              frmObj.appendTo('body');\r\n");
      out.write("              frmObj.submit();\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    function searchPopup(){ // ID/PW 찾기\r\n");
      out.write("    \tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login/user/idpass.do\";\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"mainContents\" class=\"loginContents\" >\r\n");
      out.write("\t\t<div class=\"loginContainer\">\r\n");
      out.write("\t\t\t<form id=\"form\" name=\"form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login/loginProcess.do\"\r\n");
      out.write("\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t<p class=\"loginInput\">\r\n");
      out.write("\t\t\t\t\t<label for=\"loginid\" class=\"tag\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/images/_login/login_icon01.png\" alt=\"e-mail\" /></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"loginid\" name=\"loginid\"\r\n");
      out.write("\t\t\t\t\t\tonkeydown=\"javascript:if(event.keyCode==13){fncLogin();}\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\" 아이디를 입력해주세요.\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p class=\"loginInput\">\r\n");
      out.write("\t\t\t\t\t<label for=\"password\" class=\"tag\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/images/_login/login_icon02.png\" alt=\"비밀번호\" /></label> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" id=\"password\" name=\"password\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\t\tonkeydown=\"javascript:if(event.keyCode==13){fncLogin();}\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\" 패스워드를 입력해주세요.\">\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<label for=\"idCheck\" class=\"idCheck\">\r\n");
      out.write("\t\t\t\t<!-- <input type=\"checkbox\"\tid=\"idCheck\" name=\"idCheck\">아이디 기억하기-->\r\n");
      out.write("\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t<p class=\"register\">\r\n");
      out.write("\t\t\t\t\t아이디가 없으십니까? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login/user/writeMember.do\">회원가입</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"loginBtn\" onclick=\"fncLogin()\">로그인</button>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:searchPopup();\" class=\"findPW\">비밀번호를 잊으셨나요?</a>\r\n");
      out.write("\t\t\t\t<div class=\"loginFail\"></div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- mainContents -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
