/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-18 08:45:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mng.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.go.cris.ptl.mng.menu.vo.MngMenuVo;
import kr.go.cris.ptl.mng.code.vo.MngCodeVo;
import kr.go.cris.base.controller.BaseController;
import java.util.List;

public final class listBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/jquery.treeview.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/code.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar frm_id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${frm_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar pgList = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pgList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write("\tvar linesPerPg = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${linesPerPg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar last_brd = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${last_brd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar columnList = [];\r\n");
      out.write("\tvar keyOfArr = [];\r\n");
      out.write("\tvar valueOfArr = [];\r\n");
      out.write("\tvar type_s_col = [];\r\n");
      out.write("\tvar currPg= '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currPg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar param = {};\r\n");
      out.write("\tparam.frm_id = frm_id;\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : ctxt + '/mng/form/selectTheadBoard.do',\r\n");
      out.write("\t\tdata : param,\r\n");
      out.write("\t\ttype : 'POST',\r\n");
      out.write("\t\tasync: false,  //ajax 한 function에 여러개 호출시 추가!\r\n");
      out.write("\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar optList = \"\";\r\n");
      out.write("\t\t\tvar html = \"\";\t\t\t\r\n");
      out.write("\t\t\t// 마지막은 data_typ =S인 컬럼목록(그 앞은 컬럼정보!), 뒤에서 두번째는 data_type\r\n");
      out.write("\t\t\tvar resSecFromBack= res.length -2;  \r\n");
      out.write("\t\t\tvar resTheBackmost = res.length -1;\r\n");
      out.write("/* \t\t\r\n");
      out.write("\t\t\tvar str = JSON.stringify(res[resSecFromBack]);\r\n");
      out.write("\t\t\tconsole.log(str)\r\n");
      out.write("*/\r\n");
      out.write("\t\t\tvalueOfArr = res[resSecFromBack];\r\n");
      out.write("\t\t\tkeyOfArr = Object.keys(res[resSecFromBack]);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar str = res[resTheBackmost].type_s_col;\r\n");
      out.write("\t\t\ttype_s_col = str.split(\",\");\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i=0 ; i<resSecFromBack ; i++){\r\n");
      out.write("\t\t\t\tvar checkYn = res[i].srch_yn;\r\n");
      out.write("\t\t\t\tif(checkYn==\"Y\"){\r\n");
      out.write("\t\t\t\t\toptList += '<option value=\"'+res[i].frm_col+'\">'+res[i].lbl_kor+'</option>'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar columnName = res[i].frm_col;\r\n");
      out.write("\t\t\t\tcolUpper = columnName.toUpperCase();\r\n");
      out.write("\t\t\t\tcolumnList.push(colUpper)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#wbSelect').append(optList)\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\thtml += \"<th>번호</th>\"\r\n");
      out.write("\t\t\tfor(var i=0 ; i<resSecFromBack ; i++){\r\n");
      out.write("\t\t\t\thtml += \"<th>\"+res[i].lbl_kor+\"</th>\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t$('#headInfo').html(html);\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});  //  end of ajax  .1st\r\n");
      out.write("\r\n");
      out.write("\tfn_makePg(pgList,currPg);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#searchWbBtn').click(function(){\r\n");
      out.write("\t\tvar paramObject = new Object();\r\n");
      out.write("\t\tparamObject['col'] = $('#wbSelect option:selected').val();\r\n");
      out.write("\t\tparamObject['input'] = $('#searchTxt').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfn_makePg(pgList, currPg,paramObject);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#insertWbBtn').click(function(){\r\n");
      out.write("\t\tvar lastBrd_Seq = Number(last_brd)+1;\r\n");
      out.write("\t\tcurrPg = $('#clickedPg').val();\r\n");
      out.write("\t\tcontentWndw('frm_id',frm_id,'lastBrd_Seq',lastBrd_Seq,'pg',currPg);\r\n");
      out.write("\t});\r\n");
      out.write("//\talert($('#bodyInfo').find('tr:last').find('td').eq(0).text())\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fn_makePg(pgList, currPg, searchBtn){\r\n");
      out.write("\tif(currPg==0){\r\n");
      out.write("\t\tcurrPg=1\r\n");
      out.write("\t}\r\n");
      out.write("\tvar params = {};\r\n");
      out.write("\tparams.frm_id = frm_id;\r\n");
      out.write("\tparams.currPg = currPg;\r\n");
      out.write("\tparams.linesPerPg = linesPerPg;\r\n");
      out.write("\t\r\n");
      out.write("\tif(jQuery.isEmptyObject(searchBtn)==false){\r\n");
      out.write("\t\tfor(var key in searchBtn){\r\n");
      out.write("\t\t\tif(key=='col') params.srchColumnStr = searchBtn[key];\r\n");
      out.write("\t\t\tif(key=='input') params.srchTxt = searchBtn[key];\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#pagination').css('display','none');\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : ctxt + '/mng/form/selectTbodyBoard.do',\r\n");
      out.write("\t\tdataType: 'text',\r\n");
      out.write("\t\tdata : params,\r\n");
      out.write("\t\ttype : 'POST',\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tsuccess : function(resXml){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar xmlObj = $(resXml).find('item');\r\n");
      out.write("\t\tvar html = \"\";\r\n");
      out.write("\t\tvar idx = 0;\r\n");
      out.write("\t\txmlObj.each(function(){\r\n");
      out.write("\t\t\tvar brd_seq = $(this).find('BRD_SEQ').text();\r\n");
      out.write("\t\t\thtml += '<tr>';\r\n");
      out.write("\t\t\thtml += '<td>'+brd_seq+'</td>';\r\n");
      out.write("\t\t\tfor(var i in columnList){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar data = $(this).find(columnList[i]).text();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var k in type_s_col){\r\n");
      out.write("\t\t\t\t\tif(\"COL1\"==columnList[i]){\r\n");
      out.write("\t\t\t\t\t\thtml += '<td><a href=\"javascript:contentWndw(\\'frm_id\\',\\''+frm_id+'\\',\\'no\\',\\''+brd_seq+'\\',\\'pg\\',\\''+currPg+'\\')\">'+data+'</a></td>';\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tif(type_s_col[k]==columnList[i]){\r\n");
      out.write("\t\t\t\t\t\t\tfor(var j=0 ; j<keyOfArr.length; j++){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar test = keyOfArr[j];\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data == test){\r\n");
      out.write("\t\t\t\t\t\t\t\t\thtml += '<td>'+valueOfArr[keyOfArr[j]]+'</td>';\r\n");
      out.write("\t\t\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += '<td>'+data+'</td>';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}  // end of the \"COL1\" else sentence\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\thtml += '</tr>';\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\t$('#bodyInfo').html(html);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})  // end of ajax .2nd\r\n");
      out.write("\t\r\n");
      out.write("\tvar pg_html = \"\";\r\n");
      out.write("\t\tpg_html += '<a class=\"pgList\" id=\\\"'+clickPg+'\\\"       href=\"javascript:void(0);\" onclick=\"location.reload();return false\" target=\"_self\"><<</a>';\r\n");
      out.write("\tfor(var i=0; i<pgList; i++){\r\n");
      out.write("\t\tvar clickPg = i+1;\r\n");
      out.write("\t\tpg_html += '<a class=\"pgList\" id=\\\"'+clickPg+'\\\"       href=\\\"javascript:fn_makePg('+pgList+','+clickPg+')\\\" target=\"_self\">'+clickPg+'</a>';\r\n");
      out.write("//\t\tpg_html += '<a class=\"pgList\" href=\"javascript:void(0);\" onclick=\\\"fn_makePg('+pgList+','+clickPg+'); return false;\\\" target=\"_self\">'+clickPg+'</a>';\r\n");
      out.write("\t}\r\n");
      out.write("\tpg_html += '<a class=\"pgList\" id=\\\"'+clickPg+'\\\"       href=\\\"javascript:fn_makePg('+pgList+','+pgList+')\\\" target=\"_self\">>></a>';\r\n");
      out.write("\t$('#pagination').html(pg_html);\r\n");
      out.write("\t\r\n");
      out.write("\t$('.pgList').click(function(){\r\n");
      out.write("\t\tvar clickedPg = $(this).attr('id');\r\n");
      out.write("\t\t$('#clickedPg').attr('value',clickedPg);\r\n");
      out.write("\t})\r\n");
      out.write("};\t//  end of fn  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function contentWndw(paramNm01, param01, paramNm02, param02, paramNm03, param03){\r\n");
      out.write("\t//alert($(location).attr('href')) //현재 url 받기\r\n");
      out.write("\tvar url = \"\"\r\n");
      out.write("\turl = (ctxt+\"/board/writeBoard.do\"+\"?\"+paramNm01+\"=\"+param01+\"&\"+paramNm02+\"=\"+param02+\"&\"+paramNm03+\"=\"+param03)\r\n");
      out.write("\tvar wdwObj  = window.open(url, \"_self\")\r\n");
      out.write("\t\r\n");
      out.write("} // contentWndw end\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"divRefreshArea\">\r\n");
      out.write("\t<h2>게시판</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<select id=\"wbSelect\" name=\"wbSelect\" ></select>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"searchTxt\" name=\"searchTxt\" >\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"searchWbBtn\" name=\"searchWbBtn\" value=\"검색\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\r\n");
      out.write("\t\t      <colgroup>\r\n");
      out.write("\t\t        <col style=\"width:5%\" />\r\n");
      out.write("\t\t        <col style=\"width:25%\" />\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t      </colgroup>\r\n");
      out.write("\t\t      <thead id=\"headInfo\">\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      </thead>\r\n");
      out.write("\t\t\t\t<tbody id =\"bodyInfo\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t      </table>\r\n");
      out.write("\t     <div id=\"pagination\" class=\"\"  style =\"text-align: center; letter-spacing: 15px;\"></div>   \r\n");
      out.write("\t\t<input type=\"button\" id=\"insertWbBtn\" name=\"insertWbBtn\" value=\"등록\">&nbsp;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"clickedPg\" name=\"clickedPg\" value=\"\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
