/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-09 05:00:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mng.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.go.cris.ptl.mng.menu.vo.MngMenuVo;
import kr.go.cris.ptl.mng.code.vo.MngCodeVo;
import kr.go.cris.base.controller.BaseController;
import java.util.List;

public final class writeBoard2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/jquery.treeview.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/code.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var totalPageCnt = 0;\r\n");
      out.write("var totalListCnt = 0;\r\n");
      out.write("var searchColumnArr = [];\r\n");
      out.write("var searchOptArr = [];\r\n");
      out.write("\r\n");
      out.write("var brd_seq_last = 0;\r\n");
      out.write("\r\n");
      out.write("function contentWndw(paramNm01, param01, paramNm02, param02){\r\n");
      out.write("\t//alert($(location).attr('href')) //현재 url 받기\r\n");
      out.write("\tvar url = \"\"\r\n");
      out.write("\turl = (ctxt+\"/board/writeBoard.do\"+\"?\"+paramNm01+\"=\"+param01+\"&\"+paramNm02+\"=\"+param02)\r\n");
      out.write("\tvar wdwObj  = window.open(url, \"_self\")\r\n");
      out.write("} // contentWndw end\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar frm_id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${frm_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar colNumber = \"\";\r\n");
      out.write("\tvar hdColOrder = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : ctxt+'/mng/form/selectTheadBoard.do',\r\n");
      out.write("\t\tdata : {\"frm_id\":frm_id},\r\n");
      out.write("\t\ttype: 'GET',  \r\n");
      out.write("        contentType: \"text/xml;charset=utf-8\",   \r\n");
      out.write("        dataType: 'text',\r\n");
      out.write("        async: false,  //ajax 한 function에 여러개 호출시 추가!\r\n");
      out.write("        success: function(rtnXml) {\r\n");
      out.write("\t\t\tvar xmlObj = $(rtnXml).find('item');\r\n");
      out.write("\t\t\tvar tHeadArr = [];\r\n");
      out.write("        \tvar html= \"\";\r\n");
      out.write("\r\n");
      out.write("        \tvar tmp = $(rtnXml).find('item').find('frm_col').text();\r\n");
      out.write("     \t\ttmp= tmp.replace(/col/gi ,',')\r\n");
      out.write("     \t\tcolNumber=tmp.replace(',','')\r\n");
      out.write("        //\talert(colNumber)\r\n");
      out.write("        \tvar arr = [];\r\n");
      out.write("        \tarr = colNumber.split(\",\");\r\n");
      out.write("        \t\r\n");
      out.write("        \tfor(var i in arr){\r\n");
      out.write("        \t\thdColOrder += \",\"+\"COL\"+arr[i]\t\r\n");
      out.write("        \t}\r\n");
      out.write("        \thdColOrder = hdColOrder.replace(\",\",\"\");\r\n");
      out.write("        \talert (hdColOrder)\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\ttotalPageCnt = Number($(rtnXml).find('totalPageCnt').text());\r\n");
      out.write("\t\t\t\ttotalListCnt = Number($(rtnXml).find('totalListCnt').text());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\txmlObj.each(function(){  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\ttHeadArr.push($(this).find('lbl_kor').text());\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar selectChck = $(this).find('srch_yn').text();\r\n");
      out.write("\t\t\t\t\tif(selectChck =='Y'){\r\n");
      out.write("\t\t\t\t\t\tsearchOptArr.push($(this).find('lbl_kor').text());\r\n");
      out.write("\t\t\t\t\t\tsearchColumnArr.push($(this).find('frm_col').text());\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t})  //xmlObj end\r\n");
      out.write("//thead\r\n");
      out.write("\t\t\t\thtml += '<tr>'\r\n");
      out.write("\t\t\t\thtml += '<th>순번</th>'\r\n");
      out.write("\t\t\t\ttHeadArr.forEach(function(thead){\r\n");
      out.write("\t\t\t\t\thtml += '<th>' +thead+ '</th>';\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\thtml += '</tr>'\r\n");
      out.write("\t\t\t\t$('#headInfo').html(html);\r\n");
      out.write("\t\t\t\r\n");
      out.write("// selectbox's list\r\n");
      out.write("\t\t\t  var addOpt = \"\";\t\r\n");
      out.write("\t\t\t\tfor(var i in searchOptArr){\r\n");
      out.write("\t\t\t\t\taddOpt += \"<option value=\"+searchColumnArr[i]+\">\"+searchOptArr[i]+\"</option>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('#wbSelect').append(addOpt); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})//ajax end\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar params = {}\r\n");
      out.write("\tparams.frm_id = frm_id;\r\n");
      out.write("\t\r\n");
      out.write(" \t$.ajax({\r\n");
      out.write("\t\turl : ctxt+'/mng/form/selectTbodyBoard.do',\r\n");
      out.write("\t\tdata : params,\r\n");
      out.write("\t\ttype: 'POST',  \r\n");
      out.write(" //       contentType: \"text/xml;charset=utf-8\",   \r\n");
      out.write("        dataType: 'text',\r\n");
      out.write("        async: false, \r\n");
      out.write("        success: function(rtnXml) { \r\n");
      out.write("        \talert(\"subOK\");\r\n");
      out.write("        \tvar xmlObj = $(rtnXml).find('item');\r\n");
      out.write("        \t\r\n");
      out.write("        \tvar html = \"\";\r\n");
      out.write("\t\t\tvar hdColOrderArr = [];\r\n");
      out.write("\t\t\thdColOrderArr = hdColOrder.split(\",\");\r\n");
      out.write("        \t\r\n");
      out.write("\t\t\txmlObj.each(function(){\r\n");
      out.write("\t\t\t\tvar brd_seq =  $(this).find(\"BRD_SEQ\").text() \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\thtml += '<tr>';\t\r\n");
      out.write("\t\t\t\thtml += '<td>'+ brd_seq+'</td>';\r\n");
      out.write("\t\t\t\tfor(var i in hdColOrderArr){\r\n");
      out.write("\t\t\t\t\tif(i==0){\r\n");
      out.write("\t\t\t\t\t\thtml += '<td><a href=\"javascript:contentWndw(\\'frm_id\\',\\''+frm_id+'\\',\\'detailBoard\\',\\''+brd_seq+'\\' )\">'+ $(this).find(hdColOrderArr[i]).text() +'</a></td>';\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\thtml += '<td>'+ $(this).find(hdColOrderArr[i]).text() +'</td>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\thtml += '</tr>';\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t})  // xmlObj end\r\n");
      out.write("\t\t\t\r\n");
      out.write("//\t\t\tbrd_seq 의 마지막 번호\t\t\t\r\n");
      out.write("\t\t\tbrd_seq_last = xmlObj.length+1;\r\n");
      out.write("//\t\t\t$('#pagination').val(totalPageCnt);\r\n");
      out.write("\t\t\t$('#bodyInfo').html(html);\r\n");
      out.write("        }\r\n");
      out.write("\t});  // second ajax end \r\n");
      out.write("\t\r\n");
      out.write(" \t$('#searchWbBtn').click(function(){\r\n");
      out.write(" \t\tvar searchTxt = \"\";\r\n");
      out.write(" \t\tvar wbSelect = \"\";\r\n");
      out.write(" \t\talert(\"버튼 클릭\")\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tsearchTxt = $('#searchTxt').val();\r\n");
      out.write(" \t\twbSelect = $('#wbSelect').val();\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\talert(searchTxt);\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\tvar btnParams = {};\r\n");
      out.write("\t\tbtnParams.frm_id = frm_id;\r\n");
      out.write("\t\tbtnParams.srchTxt = searchTxt;\r\n");
      out.write("\t\tbtnParams.srchColumnStr =wbSelect;\r\n");
      out.write(" \t\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : ctxt+'/mng/form/selectTbodyBoard.do',\r\n");
      out.write("\t\tdata : btnParams,\r\n");
      out.write("\t\ttype: 'GET',  \r\n");
      out.write("        contentType: \"text/xml;charset=utf-8\",   \r\n");
      out.write("        dataType: 'text',\r\n");
      out.write("        async: false, \r\n");
      out.write("        success: function(rtnXml) { \r\n");
      out.write("\r\n");
      out.write("           var xmlObj = $(rtnXml).find('item');\r\n");
      out.write("        \t\r\n");
      out.write("        \tvar html = \"\";\r\n");
      out.write("\t\t\tvar hdColOrderArr = [];\r\n");
      out.write("\t\t\thdColOrderArr = hdColOrder.split(\",\");\r\n");
      out.write("        \t\r\n");
      out.write("\t\t\txmlObj.each(function(){\r\n");
      out.write("\t\t\t\tvar brd_seq =  $(this).find(\"BRD_SEQ\").text() \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\thtml += '<tr>';\t\r\n");
      out.write("\t\t\t\thtml += '<td>'+ brd_seq+'</td>';\r\n");
      out.write("\t\t\t\tfor(var i in hdColOrderArr){\r\n");
      out.write("\t\t\t\t\tif(i==0){\r\n");
      out.write("\t\t\t\t\t\thtml += '<td><a href=\"javascript:contentWndw(\\'frm_id\\',\\''+frm_id+'\\',\\'detailBoard\\',\\''+brd_seq+'\\' )\">'+ $(this).find(hdColOrderArr[i]).text() +'</a></td>';\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\thtml += '<td>'+ $(this).find(hdColOrderArr[i]).text() +'</td>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\thtml += '</tr>';\t\r\n");
      out.write("\t\t\t})  // xmlObj end\r\n");
      out.write("\t\t\tlocation.remove;\r\n");
      out.write("\t\t\t$('#bodyInfo').html(html);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})  //ajax end   \r\n");
      out.write(" \t\t\r\n");
      out.write(" \t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#insertWbBtn').click(function(){\r\n");
      out.write("\t\t\t//새 화면 보낼때 frm_id는 보내야\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcontentWndw(\"frm_id\", frm_id, \"registerBoard\", brd_seq_last);\r\n");
      out.write("\t});  // insertWbBtn end\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})//function end\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"divRefreshArea\">\r\n");
      out.write("\t<h2>게시판</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<select id=\"wbSelect\" name=\"wbSelect\" ></select>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"searchTxt\" name=\"searchTxt\" >\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"searchWbBtn\" name=\"searchWbBtn\" value=\"검색\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\r\n");
      out.write("\t\t      <colgroup>\r\n");
      out.write("\t\t        <col style=\"width:5%\" />\r\n");
      out.write("\t\t        <col style=\"width:25%\" />\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t        <col style=\"width:10%\">\r\n");
      out.write("\t\t      </colgroup>\r\n");
      out.write("\t\t      <thead id=\"headInfo\">\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t      </thead>\r\n");
      out.write("\t\t\t\t<tbody id =\"bodyInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t      </table>\r\n");
      out.write("\t     <div id=\"pagination\" class=\"paginate\"  style =\"text-align: center;\"></div>   \r\n");
      out.write("\t\t<input type=\"button\" id=\"insertWbBtn\" name=\"insertWbBtn\" value=\"등록\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
