/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-09 02:37:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mng.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.go.cris.ptl.mng.menu.vo.MngMenuVo;
import kr.go.cris.ptl.mng.code.vo.MngCodeVo;
import kr.go.cris.base.controller.BaseController;
import java.util.List;

public final class writeBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/jquery.treeview.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/code.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar frm_id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${frm_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write("\tvar brd_seq  = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brd_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write("\tvar colNmArr = [];\r\n");
      out.write("\t\r\n");
      out.write("\tvar params = {};\r\n");
      out.write("\tparams.frm_id = frm_id;\r\n");
      out.write("\tparams.brd_seq = brd_seq;\r\n");
      out.write("\t\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#btnControl').css('display','none');\r\n");
      out.write("\talert($('#btnControl').children('#changedBtn').attr('value'))\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : ctxt+'/mng/form/selectBoardDetail.do',\r\n");
      out.write("\t\tdata : params,\r\n");
      out.write("\t\ttype :'GET',\r\n");
      out.write("\t\tcontentType : \"text/xml;charset=utf-8\",\r\n");
      out.write("\t\tdataType : 'xml',\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tsuccess : function(resXml){\r\n");
      out.write("\t\t\tvar xmlObj = $(resXml).find('item');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar colOrder = $(xmlObj).find('colOrder').text();\r\n");
      out.write("\t\t\tvar colOrdArr = [];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcolOrdArr = colOrder.split(\",\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\thtml = $(xmlObj).find('FRM_ID').text();\r\n");
      out.write("\t\t\thtml += $(xmlObj).find('BRD_SEQ').text();\r\n");
      out.write("\t\t\tfor(var i=0 ; i<colOrdArr.length;i++){\r\n");
      out.write("\t\t\t\tvar colStr =colOrdArr[i].toString();\r\n");
      out.write("\t\t\t\thtml += $(xmlObj).find(colStr).text();\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t\t\t$('#boardDetail').html(html);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor (var i in xmlObj){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcolNmArr.push((xmlObj.children())[i].nodeName);  // 컬럼명 찾기\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})  //ajax end\r\n");
      out.write("\t\r\n");
      out.write("$('#detailUpdateBtn').click(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar paramObject = new Object();\r\n");
      out.write("\tvar paramArr = [];\r\n");
      out.write("\tfor (var j in colNmArr){\r\n");
      out.write("\t\tvar tmpStr = colNmArr[j];\r\n");
      out.write("\t\tvar tmpVal = $('#'+tmpStr).val();\r\n");
      out.write("\t\tparamObject[tmpStr] = tmpVal;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tparamArr.push(paramObject);\r\n");
      out.write("\t\r\n");
      out.write("\tparams = {};\r\n");
      out.write("\tparams.jsonArr = paramArr;\r\n");
      out.write("\t\r\n");
      out.write("\t// json 방식으로 수정해보기\r\n");
      out.write(" \t$.ajax({\r\n");
      out.write("\t\turl : ctxt+'/mng/form/updatdBoardDetail.do',\r\n");
      out.write("\t\tdata : JSON.stringify(params),\r\n");
      out.write("\t\ttype :'POST',\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tsuccess : function(res){\r\n");
      out.write("\t\t\talert(\"o~k\")\r\n");
      out.write("\t\t\tlocation.reload();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})  //ajax end  \r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"divRefreshArea\">\r\n");
      out.write("\t<h2>Form 관리</h2>\r\n");
      out.write("\t\t<div id=\"boardDetail\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"test\">\r\n");
      out.write("\t\t<input type=\"button\" id=\"detailUpdateBtn\"  name=\"detailUpdateBtn\" value=\"수정\" >\r\n");
      out.write("\t\t<div id=\"btnControl\">\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"changedBtn\"  name=\"\" value=\"aaaaaa\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("     \t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
