/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-19 00:31:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("  \r\n");
      out.write("  var xmlList;\r\n");
      out.write("  var html=\"\";\r\n");
      out.write("  var curPage;\r\n");
      out.write("  var pageTotalCnt = 0;\r\n");
      out.write("  var dataTotalCnt = 0;\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("    var page =$('#page').val();\r\n");
      out.write("\tif(page == '' ){\r\n");
      out.write("\t\tpage=1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t  var searchClassification = $('#searchClassification').val();\r\n");
      out.write("\t  var searchCustomHeader = $('#searchCustomHeader').val();\r\n");
      out.write("\t  var searchSituation = $('#searchSituation').val();\r\n");
      out.write("\t\r\n");
      out.write("// reset?\r\n");
      out.write(" \tif(searchClassification != \" \" && searchCustomHeader != \" \" && searchSituation != \" \"){\r\n");
      out.write(" \t\t//select -> params\r\n");
      out.write(" \t\talert(\"공백아니면\")\r\n");
      out.write(" \t\t$(\"#view_control\").css(\"display\",\"\");\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t$('#selectClassification option[value='+searchClassification+']').attr('selected',true);\r\n");
      out.write("\t\t$('#selectCustomHeader option[value='+searchCustomHeader+']').attr('selected',true);\r\n");
      out.write("\t\t$('#selectSituation option[value='+searchSituation+']').attr('selected',true);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("$('#boardQnA_returnFirstPage').click(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$('#searchKeyword').val(\"\");\r\n");
      out.write("\t$('#selectClassification option[value=\"\" ]').attr('selected',true);\r\n");
      out.write("\t$('#selectCustomHeader option[value=\"\"]').attr('selected',true);\r\n");
      out.write("\t$('#selectSituation option[value=\"\"]').attr('selected',true);\r\n");
      out.write("\t\r\n");
      out.write("\tfn_search(1);\r\n");
      out.write("});\r\n");
      out.write("// boardQnA_returnFirstPage end\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t// 화면 목록 조회\r\n");
      out.write("\tfn_search(page);\r\n");
      out.write("\t\r\n");
      out.write("\t $(\"#searchKeyword\").keydown(function(e){\r\n");
      out.write("\t\tif(e.ctrlKey && ( e.which === 77 )) {\r\n");
      out.write("\t\t\t$(\".excelDown\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("    });  \r\n");
      out.write("});  // first function end\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("function detailed_information(param){\r\n");
      out.write("\t\r\n");
      out.write("\t var selectClassification = $('#selectClassification option:selected').val();\r\n");
      out.write("\t var selectCustomHeader = $('#selectCustomHeader option:selected').val();\r\n");
      out.write("\t var selectSituation = $('#selectSituation option:selected').val();\r\n");
      out.write("\r\n");
      out.write("\t$('#idx_board').val(param);\r\n");
      out.write("\t$('#searchClassification').val(selectClassification);\r\n");
      out.write("\t$('#searchCustomHeader').val(selectCustomHeader) ;\r\n");
      out.write("\t$('#searchSituation').val(selectCustomHeader);\r\n");
      out.write("\t\r\n");
      out.write("\tvar form=document.reqForm;\r\n");
      out.write("\tform.action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/board/qna/boardQnaListDetailed.do\";\r\n");
      out.write("\tform.submit();\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("// 검색 후 페이지 1 누르면 그냥 초기화 (검색 결과나온 1 페이지 유지 안됨)\r\n");
      out.write("function fn_search(page){\r\n");
      out.write("\t\r\n");
      out.write("\tcurPage= page;\r\n");
      out.write("\t\r\n");
      out.write("\t$('#page').val(curPage);\r\n");
      out.write("\tvar params = {};\r\n");
      out.write("  \t\tparams.page=curPage;\r\n");
      out.write("  \t\tparams.searchKeyword = $('#searchKeyword').val();\r\n");
      out.write("\t\tparams.searchClassification  = $('#selectClassification option:selected').val();\r\n");
      out.write("\t\tparams.searchCustomHeader = $('#selectCustomHeader option:selected').val(); \r\n");
      out.write("\t\tparams.searchSituation = $('#selectSituation option:selected').val(); \r\n");
      out.write("\t\t\r\n");
      out.write("$.ajax({\r\n");
      out.write("        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/board/qna/boardQnaList.do',\r\n");
      out.write("        data: params,\r\n");
      out.write("        type: 'POST',\r\n");
      out.write("        dataType: 'text',\r\n");
      out.write("        cache: false,\r\n");
      out.write("        success: function(rtnXml) {  \r\n");
      out.write("\r\n");
      out.write("        \txmlList = $(rtnXml).find('item');\r\n");
      out.write("\r\n");
      out.write("       \t\tpageTotalCnt=0;\r\n");
      out.write("        \tdataTotalCnt=0; \r\n");
      out.write("        \t\r\n");
      out.write("        \thtml=\"\";\r\n");
      out.write("\t\t\tif(xmlList.length > 0){\r\n");
      out.write("\t\t\t\t//총페이지수\r\n");
      out.write("\t\t\t\tpageTotalCnt = Number($(rtnXml).find('totalPageCnt').text());\r\n");
      out.write("\t\t\t\tdataTotalCnt = Number($(rtnXml).find('totalDataCnt').text()); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\txmlList.each(function(cnt){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tvar obj = $(this);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar idx_board = obj.find('idx_board').text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t/***************************************************************\r\n");
      out.write("\t\t\t\t\t* 화면별로 따로 세팅 테이블 데이터\r\n");
      out.write("\t\t\t\t\t****************************************************************/\r\n");
      out.write("\t\t\t\t\thtml += '<tr>';\r\n");
      out.write("\t\t\t\t\thtml += ' <td >'+obj.find('rn').text() + '</td>';\r\n");
      out.write("\t\t\t\t\thtml += ' <td style=\"text-align: center\">'+obj.find('classification').text() + '</td>';\r\n");
      out.write("\t\t\t\t\thtml += ' <td ><a href=\"javascript:detailed_information(\\''+idx_board+'\\')\" >'+obj.find('title').text() + '</td>';\r\n");
      out.write("\t\t\t\t\thtml += ' <td style=\"text-align: center\">'+obj.find('writer').text() + '</td>';\r\n");
      out.write("\t\t\t\t\thtml += ' <td style=\"text-align: center\">'+obj.find('insertdate_board').text() + '</td>';\r\n");
      out.write("\t\t\t\t\thtml += ' <td style=\"text-align: center\">'+obj.find('situation').text() +'</td>';\r\n");
      out.write("\t\t\t\t\thtml += '</tr>';\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t\t\t//페이징처리\r\n");
      out.write("\t\t\t    $('#paging').paging({\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t current:curPage\r\n");
      out.write("\t\t\t\t\t,max:pageTotalCnt\r\n");
      out.write("\t\t\t\t\t,length:pageLen\r\n");
      out.write("\t\t\t\t\t,onclick:function(e,page){\r\n");
      out.write("\t\t\t\t\t\tcurPage = page;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// 페이지 이동시 PARAM 초기화\r\n");
      out.write("\t\t\t\t\t\t$(\"#searchKeyword\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#selectClassification\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#selectCustomHeader\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#selectSituation\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfn_search(curPage);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t\t\t$(\"#topPageInfo\").html(\"<span class = 'gray'>[\"+ curPage +\" / \"+pageTotalCnt+\" Pages]</span> <span class = 'txt-red' >\"+dataTotalCnt+\"</span> 건이 검색되었습니다.\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#bodyInfo\").html(html);\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t/***************************************************************\r\n");
      out.write("\t\t\t\t*          화면별로 따로 세팅 테이블 데이터 조회 없는경우\r\n");
      out.write("\t\t\t\t****************************************************************/\r\n");
      out.write("\t\t\t\t$('#paging').children().remove();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#bodyInfo\").html('<tr><td colspan=\"5\" style=\"text-align: center\" >조회된 내용이 없습니다.</td></tr>');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        },\r\n");
      out.write("        error : function(){                              \r\n");
      out.write("        \t// Ajax 전송 에러 발생시 실행\r\n");
      out.write("          fn_alert('오류가 발생했습니다.<br /> 관리자에게 문의 바랍니다.','e');\r\n");
      out.write("        }\r\n");
      out.write("        \t\r\n");
      out.write("}); \r\n");
      out.write("  //ajax end\r\n");
      out.write("  }; \r\n");
      out.write("  //function end\r\n");
      out.write("$(function(){\r\n");
      out.write("$(\"#testBtn\").click(function(){\r\n");
      out.write("\talert(\"sh c foreact\")\r\n");
      out.write("\talert($('#QnA_CLASSIFICATION option:selected').val())\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title></title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  <form name=\"reqForm\" method=\"post\">\r\n");
      out.write("    <div class=\"search_section\">\r\n");
      out.write("      <select id=\"selectClassification\" name=\"selectClassification\">\r\n");
      out.write("      <option value=\"\">분류</option>\r\n");
      out.write("      <option value=\"member\">회원관련</option>\r\n");
      out.write("      <option value=\"clinical-research\">임상연구관련</option>\r\n");
      out.write("      <option value=\"registration\">등록관련</option>\r\n");
      out.write("      <option value=\"theOthers\">기타</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\r\n");
      out.write("    <select id=\"selectCustomHeader\" name=\"selectCustomHeader\">\r\n");
      out.write("    \t<option value=\"\">제목/작성자</option>\r\n");
      out.write("      <option value=\"cstmhdr-title\">제목</option>\r\n");
      out.write("      <option value=\"cstmhdr-writer\">작성자</option>\r\n");
      out.write("    </select>\r\n");
      out.write("\r\n");
      out.write("    <select id=\"selectSituation\" name=\"selectSituation\">\r\n");
      out.write("      <option value=\"\">상태</option>\r\n");
      out.write("      <option value=\"req-cmplt\">신청완료</option>\r\n");
      out.write("      <option value=\"ans-ing\">답변중</option>\r\n");
      out.write("      <option value=\"ans-cmplt\">답변완료</option>\r\n");
      out.write("    </select>\r\n");
      out.write("    \r\n");
      out.write("      <input type=\"text\" id=\"searchKeyword\" name=\"searchKeyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardQnAVo.searchKeyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"   placeholder=\"제목 또는 작성자를 입력 하세요.\">\r\n");
      out.write("      <input type=\"button\" id=\"searchBtn\" name=\"\" value=\"검색\" onclick=\"javascript:fn_search(1)\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <p id=\"topPageInfo\"></p>\r\n");
      out.write("    <div class=\"table_section\">\r\n");
      out.write("      <table>\r\n");
      out.write("   \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<select>\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</select>  \r\n");
      out.write("\r\n");
      out.write("<select>\r\n");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</select>  \r\n");
      out.write("\r\n");
      out.write("<select>\r\n");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</select>  \r\n");
      out.write("<input type=\"button\" id=\"testBtn\" name=\"testBtn\" value=\"test\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <colgroup>\r\n");
      out.write("        <col style=\"width:5%\" />\r\n");
      out.write("        <col style=\"width:10%\" />\r\n");
      out.write("        <col style=\"width:35%\">\r\n");
      out.write("        <col style=\"width:25%\">\r\n");
      out.write("        <col style=\"width:15%\">\r\n");
      out.write("        <col style=\"width:10%\">\r\n");
      out.write("      </colgroup>\r\n");
      out.write("      <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>번호</th><th>분류</th><th>제목</th><th>작성자</th><th>등록일</th><th>상태</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("\t\t<tbody id = \"bodyInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    \r\n");
      out.write("     <input type=\"text\" id=\"message\" name=\"message\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" alt=\"message\">\r\n");
      out.write("\t<input type=\"text\" name=\"page\" id=\"page\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardQnAVo.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" alt=\"pageNum\" /> \r\n");
      out.write(" \t<input type=\"text\" name=\"searchClassification\" id=\"searchClassification\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardQnAVo.searchClassification}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> \r\n");
      out.write("\t<input type=\"text\" name=\"searchCustomHeader\" id=\"searchCustomHeader\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardQnAVo.searchCustomHeader}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  /> <!-- writer 추가 -->\r\n");
      out.write("\t<input type=\"text\" name=\"searchSituation\" id=\"searchSituation\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardQnAVo.searchSituation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> \r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"idx_board\" id=\"idx_board\" /> \r\n");
      out.write("</form>\r\n");
      out.write("\t<div id=\"paging\" class=\"paginate\"  style =\"text-align: center;\">\r\n");
      out.write("              <input type=\"button\" value=\"등록\"  id=\"boardQnA_register\">\r\n");
      out.write("    </div>\r\n");
      out.write(" \t<div id=\"view_control\" style=\"display:none\">\r\n");
      out.write("              \t<input type=\"button\" value=\"첫 화면으로 이동\"  id=\"boardQnA_returnFirstPage\" >\r\n");
      out.write("     </div>\r\n");
      out.write("  </body>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/board/board_list.jsp(225,0) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_CLASSIFICATION }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/board/board_list.jsp(225,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("QnA_CLASSIFICATION");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_CLASSIFICATION.cd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_CLASSIFICATION.cd_nm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/board/board_list.jsp(231,0) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_CustomHeader }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/board/board_list.jsp(231,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("QnA_CustomHeader");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_CustomHeader.cd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_CustomHeader.cd_nm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/views/board/board_list.jsp(237,0) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_SITUATION }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/board/board_list.jsp(237,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("QnA_SITUATION");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_SITUATION.cd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${QnA_SITUATION.cd_nm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }
}
