/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-04-21 01:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.go.cris.ptl.mng.menu.vo.MngMenuVo;

public final class columnAbbreviation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/jquery.treeview.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resources/css/tree/code.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var theNBofRows = 0;\r\n");
      out.write("var theNBofPartRows = 20;\r\n");
      out.write("var selectedPg = 0;\r\n");
      out.write("var pileofFigures = 0;\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : ctxt+'/board/columnAbbreviation/colAbbrevtView.do',\r\n");
      out.write("\t\ttype :'POST',\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tsuccess : function(res){\r\n");
      out.write("\t\t\ttheNBofRows =  res.idx;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar currentUrl  = $(location).attr('href');\r\n");
      out.write("\t\t\tvar startFor = 0;\r\n");
      out.write("\t\t\tif(currentUrl.includes(\"pg\")){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar currentPg = 0;\r\n");
      out.write("\t\t\t\tcurrentPg = fn_getUrlParam(currentUrl,0,1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tstartFor = (currentPg-1)*theNBofPartRows+1;\r\n");
      out.write("\t\t\t\tforIdx =  (currentPg)*theNBofPartRows+1;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tpileofFigures += (currentPg)*theNBofPartRows;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(pileofFigures>theNBofRows){\r\n");
      out.write("\t\t\t\t\tforIdx =  ((currentPg-1)*theNBofPartRows)+theNBofRows-((currentPg-1)*theNBofPartRows);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#selectedPgInfo').attr('value',currentPg);\r\n");
      out.write("\t\t\t\tselectedPg = $('#selectedPgInfo').val();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#divPgList').css('display','none');\r\n");
      out.write("\t\t\t\t$('#changePgBtn').attr({'value':'분할 하기','style':'margin-left:50%;'});\r\n");
      out.write("\t\t\t\tstartFor = 1;\r\n");
      out.write("\t\t\t\tforIdx = theNBofRows;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tfor(var i=startFor ; i<forIdx ;i++){\r\n");
      out.write("\t\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+i+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+res.colOrgnArr[i]+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += \"<td>\"+res.colAbbrvt[i]+\"</td>\";\r\n");
      out.write("\t\t\t\thtml += '<td><div class=\"showText\"><input type=\"text\" class=\"ipModify\"></div></td>';\r\n");
      out.write("\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#colList').html(html); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t});  //  the end of a ajax\r\n");
      out.write("\t\r\n");
      out.write("\t$('.showText').css('display','none');\r\n");
      out.write("\tvar pgCnt =0 ;\r\n");
      out.write("\tif(selectedPg !=0){\r\n");
      out.write("\t\t$('#divPgList').css('display','inline');\r\n");
      out.write("\t\tfn_makePgList(Number(theNBofRows), Number(selectedPg));\r\n");
      out.write("\t\t$('#changePgBtn').attr({'value':'한 화면에 보기','style':'margin-left:auto;' });\r\n");
      out.write("\t\tpgCnt++;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#changePgBtn').click(function(){\r\n");
      out.write("\t\tif(pgCnt==0){\r\n");
      out.write("\t\t\t$('#selectedPgInfo').attr('value',1);\r\n");
      out.write("\t\t\t$('#divPgList').css('display','inline');\r\n");
      out.write("\t\t\tfn_makePgList(Number(theNBofRows),1);\r\n");
      out.write("\t\t\tchangeUrl(1)\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#divPgList').css('display','none');\r\n");
      out.write("\t\t\tchangeUrl(\"Y\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}) // the end of a button\r\n");
      out.write("\t\r\n");
      out.write("\tvar modifyCtn = 0;\r\n");
      out.write("\t$('#modifyBtn').click(function(){\r\n");
      out.write("\t\t$('.showText').css('display','');\r\n");
      out.write("\t\t$('#modifyBtn').attr('value','입력');\r\n");
      out.write("//alert($(this).parents('tr').find(\":input\").val())\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});   //  the end of a function\r\n");
      out.write("\r\n");
      out.write("function fn_makePgList(theNumberOfRows, currentPg){\r\n");
      out.write("\tvar pgList = Math.ceil(theNumberOfRows/theNBofPartRows);\r\n");
      out.write("\tvar html = \"\";\r\n");
      out.write("\tfor(i=0 ; i<pgList ; i++){\r\n");
      out.write("\t\tvar pgNb = i+1;\r\n");
      out.write("\t\thtml += \"<input type=\\\"radio\\\" id=\\\"pg\"+pgNb+\"\\\" name=\\\"pgBtn\\\" value=\\\"pg\"+pgNb+\"\\\" onclick=\\\"changeUrl(\"+pgNb+\")\\\"\";\r\n");
      out.write("\t\t\tif(currentPg == pgNb) html+=\"checked\";\r\n");
      out.write("\t\thtml +=\">\";\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#divPgList').html(html);\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function changeUrl(pgNmbr){\r\n");
      out.write("\tvar beforeUrl = $(location).attr('href');\r\n");
      out.write("\t\r\n");
      out.write("\tvar urlIdx = beforeUrl.indexOf(\"?\",1);\r\n");
      out.write("\tbeforeUrl = beforeUrl.replace(beforeUrl.substring(urlIdx),\"\");\r\n");
      out.write("\tif(pgNmbr != \"Y\"){\r\n");
      out.write("\t\tvar url = beforeUrl+\"?pg=\"+pgNmbr;\r\n");
      out.write("\t\tlocation.replace(url);\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tlocation.replace(beforeUrl);\r\n");
      out.write("\t}\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function fn_getUrlParam(url, arrIdx, strIdx){\r\n");
      out.write("\tarrIdx = Number(arrIdx);\r\n");
      out.write("\tstrIdx = Number(strIdx);\r\n");
      out.write("\t\r\n");
      out.write("\tvar ipArr = [];\r\n");
      out.write("\tvar resultStr = \"\";\r\n");
      out.write("\tipArr = url.split(\"&\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar tmpStr = ipArr[arrIdx].toString();\r\n");
      out.write("\tipArr = tmpStr.split(\"=\");\r\n");
      out.write("\t\r\n");
      out.write("\tresultStr = ipArr[strIdx].toString();\r\n");
      out.write("\treturn resultStr;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\" style=\"min-height: 600px;\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"divRefreshArea\">\r\n");
      out.write("\t\t\t<h2 style=\"margin-left: 10%;\">약어 목록</h2>\r\n");
      out.write("     \t<div id=\"divPgList\" style=\"margin-left: 45%;\"></div>\r\n");
      out.write("\t\t<input type=\"button\" id=\"changePgBtn\" name=\"changePgBtn\" value=\"\" >\r\n");
      out.write("\t\t<input type=\"button\" id=\"modifyBtn\" name=\"modifyBtn\" value=\"수정요청\" >\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"selectedPgInfo\" name=\"selectedPgInfo\" value=\"\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"\" name=\"etl_form\">\r\n");
      out.write("\t     \t<table id=\"example0\" class=\"tbl_type\"  style=\"width:50%;margin-left: 10%;\"> \r\n");
      out.write("\t        \t<colgroup>\r\n");
      out.write("\t\t           \t<col width=\"8%\" />\r\n");
      out.write("\t\t           \t<col width=\"21%\" />\r\n");
      out.write("\t\t            <col width=\"21%\" />\r\n");
      out.write("\t           </colgroup> \r\n");
      out.write("\t\t           <thead>    \r\n");
      out.write("\t\t         \t<tr>            \r\n");
      out.write("\t\t         \t\t<th>번호</th>    \r\n");
      out.write("\t\t         \t\t<th>원래 컬럼명</th>    \r\n");
      out.write("\t\t\t            <th>약어</th>    \r\n");
      out.write("\t\t        \t </tr>        \r\n");
      out.write("\t\t       \t</thead>\r\n");
      out.write("\t\t       \t<tbody id=\"colList\" >       \r\n");
      out.write("\t\t        </tbody>\t\t        \r\n");
      out.write("\t     \t</table>\t\t\r\n");
      out.write("     \t</form>\r\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
