
/**
 * 프로그램 : 게시판 FAQ 파일
 * 테이블명 : BOARD_FAQ_FILE
 */
ALTER TABLE RECRUIT.BOARD_FAQ_FILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.BOARD_FAQ_FILE CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.BOARD_FAQ_FILE
(
  FAQ_SN        NUMBER(22),
  FILE_SN       NUMBER(22),
  FILE_CONV_NM  VARCHAR2(512 BYTE),
  FILE_PATH     VARCHAR2(2000 BYTE),
  FILE_NM       VARCHAR2(512 BYTE),
  FILE_SIZE     NUMBER(22),
  DEL_YN        VARCHAR2(1 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.BOARD_FAQ_FILE IS '게시판 FAQ파일';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.FAQ_SN IS 'FAQ 순번(FK)';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.FILE_SN IS '파일순번';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.FILE_CONV_NM IS '파일 변환 명';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.FILE_PATH IS '파일 경로';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.FILE_NM IS '파일 명';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.FILE_SIZE IS '파일 크기';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.DEL_YN IS '삭제 여부';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.BOARD_FAQ_FILE.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT.BOARD_FAQ_FILE_PK ON RECRUIT.BOARD_FAQ_FILE
(FAQ_SN, FILE_SN)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.BOARD_FAQ_FILE ADD (
  CONSTRAINT BOARD_FAQ_FILE_PK
 PRIMARY KEY
 (FAQ_SN, FILE_SN)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));
               
               
/**
 * 프로그램 : 게시판 
 * 테이블명 : BOARD_NOTI
 */               
ALTER TABLE RECRUIT.BOARD_NOTI
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.BOARD_NOTI CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.BOARD_NOTI
(
  NOTI_SN       NUMBER(22),
  NOTI_TITL     VARCHAR2(512 BYTE),
  NOTI_CTTS     CLOB,
  RD_CNT        NUMBER(22),
  CHK           VARCHAR2(1 BYTE),
  DEL_YN        VARCHAR2(1 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (NOTI_CTTS) STORE AS (
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  INDEX       (
        TABLESPACE SYSTEM
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   ))
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  FREELISTS        1
                  FREELIST GROUPS  1
                  BUFFER_POOL      DEFAULT
                 ))
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.BOARD_NOTI IS '게시판 공지사항';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.NOTI_SN IS '공지사항 순번';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.NOTI_TITL IS '공지사항 제목';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.NOTI_CTTS IS '공지사항 내용';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.RD_CNT IS '조회 수';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.CHK IS '메인게시여부';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.DEL_YN IS '삭제여부';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT.PK_USERS ON RECRUIT.BOARD_NOTI
(NOTI_SN)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.BOARD_NOTI ADD (
  CONSTRAINT PK_USERS
 PRIMARY KEY
 (NOTI_SN)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));
/**
 * 프로그램 : 게시판 파일 
 * 테이블명 : BOARD_NOTI_FILE
 */     
 ALTER TABLE RECRUIT.BOARD_NOTI_FILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.BOARD_NOTI_FILE CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.BOARD_NOTI_FILE
(
  NOTI_SN       NUMBER(22),
  FILE_SN       NUMBER(22),
  FILE_CONV_NM  VARCHAR2(512 BYTE),
  FILE_PATH     VARCHAR2(2000 BYTE),
  FILE_NM       VARCHAR2(512 BYTE),
  FILE_SIZE     NUMBER(22),
  DEL_YN        VARCHAR2(1 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.BOARD_NOTI_FILE IS '게시판 공지사항 파일';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.NOTI_SN IS '공지사항 순번';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.FILE_SN IS '파일 순번';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.FILE_CONV_NM IS '파일 변환 명';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.FILE_PATH IS '파일 경로';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.FILE_NM IS '파일 명';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.FILE_SIZE IS '파일 크기';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.DEL_YN IS '삭제 여부';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.BOARD_NOTI_FILE.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT.PK_USERS1 ON RECRUIT.BOARD_NOTI_FILE
(NOTI_SN, FILE_SN)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.BOARD_NOTI_FILE ADD (
  CONSTRAINT PK_USERS1
 PRIMARY KEY
 (NOTI_SN, FILE_SN)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));
/**
 * 프로그램 : 팝업 관리 
 * 테이블명 : BOARD_POPUP
 */    
ALTER TABLE RECRUIT.BOARD_POPUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.BOARD_POPUP CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.BOARD_POPUP
(
  POP_SN        NUMBER(22),
  POP_TITL      VARCHAR2(512 BYTE),
  POP_CTTS      VARCHAR2(4000 BYTE),
  POP_LINK      VARCHAR2(500 BYTE),
  POP_STR_DT    VARCHAR2(8 BYTE),
  POP_END_DT    VARCHAR2(8 BYTE),
  POST_YN       VARCHAR2(1 BYTE),
  DEL_YN        VARCHAR2(1 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.BOARD_POPUP IS '팝업관리';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.POP_SN IS '팝업 순번';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.POP_TITL IS '팝업 제목';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.POP_CTTS IS '팝업 내용';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.POP_LINK IS '팝업 링크';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.POP_STR_DT IS '팝업 시작 일자';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.POP_END_DT IS '팝업 종료 일자';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.POST_YN IS '게시 여부';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.DEL_YN IS '삭제 여부';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT.BOARD_POPUP_PK ON RECRUIT.BOARD_POPUP
(POP_SN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.BOARD_POPUP ADD (
  CONSTRAINT BOARD_POPUP_PK
 PRIMARY KEY
 (POP_SN)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
/**
 * 프로그램 : 팝업 관리 파일
 * 테이블명 : BOARD_POPUP_FILE
 */        
ALTER TABLE RECRUIT.BOARD_POPUP_FILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.BOARD_POPUP_FILE CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.BOARD_POPUP_FILE
(
  POP_SN        NUMBER(22)                      NOT NULL,
  FILE_SN       NUMBER(22)                      NOT NULL,
  FILE_CONV_NM  VARCHAR2(512 BYTE),
  FILE_PATH     VARCHAR2(2000 BYTE),
  FILE_NM       VARCHAR2(512 BYTE),
  FILE_SIZE     NUMBER,
  DEL_YN        VARCHAR2(1 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.BOARD_POPUP_FILE IS '게시판 팝업 첨부파일';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.POP_SN IS '팝업 순번';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.FILE_SN IS '파일 순번';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.FILE_CONV_NM IS '파일 변환 명';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.FILE_PATH IS '파일 경로';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.FILE_NM IS '파일 명';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.FILE_SIZE IS '파일 크기';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.DEL_YN IS '삭제 여부';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.BOARD_POPUP_FILE.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT.BOARD_POPUP_FILE_PK ON RECRUIT.BOARD_POPUP_FILE
(POP_SN, FILE_SN)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.BOARD_POPUP_FILE ADD (
  CONSTRAINT BOARD_POPUP_FILE_PK
 PRIMARY KEY
 (POP_SN, FILE_SN)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));
/**
 * 프로그램 : 코드 관리
 * 테이블명 : CD_MNG
 */  
ALTER TABLE RECRUIT.CD_MNG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.CD_MNG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.CD_MNG
(
  UP_CD        VARCHAR2(20 BYTE)                NOT NULL,
  CD           VARCHAR2(20 BYTE)                NOT NULL,
  CD_NM        VARCHAR2(200 BYTE),
  CD_DESC      VARCHAR2(1000 BYTE),
  CD_ORD       NUMBER,
  REF_VAL1     VARCHAR2(1000 BYTE),
  REF_VAL2     VARCHAR2(1000 BYTE),
  REF_VAL3     VARCHAR2(1000 BYTE),
  USE_YN       VARCHAR2(20 BYTE)                DEFAULT 'N',
  CREATE_DTTM  DATE,
  CREATE_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.CD_MNG IS '코드관리';

COMMENT ON COLUMN RECRUIT.CD_MNG.UP_CD IS '상위 공통 코드';

COMMENT ON COLUMN RECRUIT.CD_MNG.CD IS '공통 코드';

COMMENT ON COLUMN RECRUIT.CD_MNG.CD_NM IS '코드 명';

COMMENT ON COLUMN RECRUIT.CD_MNG.CD_DESC IS '코드 설명';

COMMENT ON COLUMN RECRUIT.CD_MNG.CD_ORD IS '코드 정렬 순서';

COMMENT ON COLUMN RECRUIT.CD_MNG.REF_VAL1 IS '참조 칼럼 1 내용';

COMMENT ON COLUMN RECRUIT.CD_MNG.REF_VAL2 IS '참조 칼럼 2 내용';

COMMENT ON COLUMN RECRUIT.CD_MNG.REF_VAL3 IS '참조 칼럼 3 내용';

COMMENT ON COLUMN RECRUIT.CD_MNG.USE_YN IS '사용여부';

COMMENT ON COLUMN RECRUIT.CD_MNG.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.CD_MNG.CREATE_ID IS '생성자 ID';


CREATE UNIQUE INDEX RECRUIT.CD_MNG_PK ON RECRUIT.CD_MNG
(UP_CD, CD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.CD_MNG ADD (
  CONSTRAINT CD_MNG_PK
 PRIMARY KEY
 (UP_CD, CD)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
/**
 * 프로그램 : 컬럼 정보
 * 테이블명 : COL_INFO
 */ 
ALTER TABLE RECRUIT.COL_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.COL_INFO CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.COL_INFO
(
  TABLE_NAME   VARCHAR2(200 BYTE)               NOT NULL,
  COLUMN_NAME  VARCHAR2(200 BYTE)               NOT NULL,
  CONTENT_YN   CHAR(1 BYTE),
  PK_YN        CHAR(1 BYTE),
  TITLE_YN     CHAR(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.COL_INFO IS '컬럼정보';

COMMENT ON COLUMN RECRUIT.COL_INFO.TABLE_NAME IS '테이블명';

COMMENT ON COLUMN RECRUIT.COL_INFO.COLUMN_NAME IS '컬럼명';

COMMENT ON COLUMN RECRUIT.COL_INFO.CONTENT_YN IS '컨텐츠여부';

COMMENT ON COLUMN RECRUIT.COL_INFO.PK_YN IS 'PK여부';

COMMENT ON COLUMN RECRUIT.COL_INFO.TITLE_YN IS '타이틀여부';


CREATE INDEX RECRUIT.COL_INFO_IDX ON RECRUIT.COL_INFO
(TABLE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RECRUIT.PK_COL_INFO ON RECRUIT.COL_INFO
(TABLE_NAME, COLUMN_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.COL_INFO ADD (
  CONSTRAINT COL_INFO_PK
 PRIMARY KEY
 (TABLE_NAME, COLUMN_NAME));
/**
 * 프로그램 : 키워드 정보
 * 테이블명 : KEYWORD_INFO
 */  
ALTER TABLE RECRUIT.KEYWORD_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.KEYWORD_INFO CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.KEYWORD_INFO
(
  KEYWORD_SEQ  NUMBER(22)                       NOT NULL,
  KEYWORD_NM   VARCHAR2(200 BYTE)               NOT NULL,
  HIT          NUMBER(22)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.KEYWORD_INFO IS '키워드정보';

COMMENT ON COLUMN RECRUIT.KEYWORD_INFO.KEYWORD_SEQ IS '키워드순번';

COMMENT ON COLUMN RECRUIT.KEYWORD_INFO.KEYWORD_NM IS '키워드명';

COMMENT ON COLUMN RECRUIT.KEYWORD_INFO.HIT IS '사용횟수';


CREATE INDEX RECRUIT.KEYWORD_INFO_IDX ON RECRUIT.KEYWORD_INFO
(KEYWORD_NM)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RECRUIT.KEYWORD_INFO_R_IDX ON RECRUIT.KEYWORD_INFO
(KEYWORD_SEQ, KEYWORD_NM)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RECRUIT.PK_KEYWORD_INFO ON RECRUIT.KEYWORD_INFO
(KEYWORD_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.KEYWORD_INFO ADD (
  CONSTRAINT KEYWORD_INFO_PK
 PRIMARY KEY
 (KEYWORD_SEQ));

 /**
 * 프로그램 : 키워드 관리
 * 테이블명 : KEYWORD_MNG
 */  
ALTER TABLE RECRUIT.KEYWORD_MNG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.KEYWORD_MNG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.KEYWORD_MNG
(
  KEYWORD_SEQ  NUMBER(22)                       NOT NULL,
  TABLE_NAME   VARCHAR2(200 BYTE)               NOT NULL,
  SAVE_DATE    DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RECRUIT.KEYWORD_MNG.KEYWORD_SEQ IS '키워드순번';

COMMENT ON COLUMN RECRUIT.KEYWORD_MNG.TABLE_NAME IS '테이블명';

COMMENT ON COLUMN RECRUIT.KEYWORD_MNG.SAVE_DATE IS '검색순번';


CREATE INDEX RECRUIT.KEYWORD_MNG_IDX ON RECRUIT.KEYWORD_MNG
(KEYWORD_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RECRUIT.PK_KEYWORD_MNG ON RECRUIT.KEYWORD_MNG
(KEYWORD_SEQ, TABLE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.KEYWORD_MNG ADD (
  CONSTRAINT KEYWORD_MNG_PK
 PRIMARY KEY
 (KEYWORD_SEQ, TABLE_NAME));
 
 /**
 * 프로그램 : 키워드 테이블정보
 * 테이블명 : KEYWORD_TAB_INFO
 */  
ALTER TABLE RECRUIT.KEYWORD_TAB_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.KEYWORD_TAB_INFO CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.KEYWORD_TAB_INFO
(
  KEYWORD_SEQ      NUMBER(22)                   NOT NULL,
  KEYWORD_TAB_SEQ  NUMBER(22)                   NOT NULL,
  TABLE_NAME       VARCHAR2(200 BYTE)           NOT NULL,
  TABLE_SEQ        VARCHAR2(200 BYTE)           NOT NULL,
  TABLE_TITLE      VARCHAR2(500 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.KEYWORD_TAB_INFO IS '키워드테이블관리';

COMMENT ON COLUMN RECRUIT.KEYWORD_TAB_INFO.KEYWORD_SEQ IS '키워드순번';

COMMENT ON COLUMN RECRUIT.KEYWORD_TAB_INFO.KEYWORD_TAB_SEQ IS '키워드상세순번';

COMMENT ON COLUMN RECRUIT.KEYWORD_TAB_INFO.TABLE_NAME IS '테이블명';

COMMENT ON COLUMN RECRUIT.KEYWORD_TAB_INFO.TABLE_SEQ IS '테이블순번';

COMMENT ON COLUMN RECRUIT.KEYWORD_TAB_INFO.TABLE_TITLE IS '타이틀명';


CREATE INDEX RECRUIT.KEYWORD_TAB_INFO_IDX ON RECRUIT.KEYWORD_TAB_INFO
(KEYWORD_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RECRUIT.KEYWORD_TAB_INFO_TB_IDX ON RECRUIT.KEYWORD_TAB_INFO
(TABLE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RECRUIT.PK_KEYWORD_TAB_INFO ON RECRUIT.KEYWORD_TAB_INFO
(KEYWORD_SEQ, KEYWORD_TAB_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.KEYWORD_TAB_INFO ADD (
  CONSTRAINT KEYWORD_TAB_INFO_PK
 PRIMARY KEY
 (KEYWORD_SEQ, KEYWORD_TAB_SEQ));

/**
 * 프로그램 : 테이블정보
 * 테이블명 : TAB_INFO
 */ 
ALTER TABLE RECRUIT.TAB_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.TAB_INFO CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.TAB_INFO
(
  TABLE_NAME   VARCHAR2(200 BYTE)               NOT NULL,
  TABLE_GP     VARCHAR2(200 BYTE)               NOT NULL,
  USE_YN       CHAR(1 BYTE),
  TABLE_URL    VARCHAR2(300 BYTE),
  TABLE_WHERE  VARCHAR2(500 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.TAB_INFO IS '테이블정보';

COMMENT ON COLUMN RECRUIT.TAB_INFO.TABLE_NAME IS '테이블명';

COMMENT ON COLUMN RECRUIT.TAB_INFO.TABLE_GP IS '테이블그룹';

COMMENT ON COLUMN RECRUIT.TAB_INFO.USE_YN IS '사용여부';

COMMENT ON COLUMN RECRUIT.TAB_INFO.TABLE_URL IS '테이블URL';

COMMENT ON COLUMN RECRUIT.TAB_INFO.TABLE_WHERE IS '조회조건';


CREATE UNIQUE INDEX RECRUIT.PK_TAB_INFO ON RECRUIT.TAB_INFO
(TABLE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.TAB_INFO ADD (
  CONSTRAINT TAB_INFO_PK
 PRIMARY KEY
 (TABLE_NAME)); 
 
/**
 * 프로그램 : 메뉴관리
 * 테이블명 : MENU_MNG
 */
ALTER TABLE RECRUIT.MENU_MNG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.MENU_MNG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.MENU_MNG
(
  MENU_ID       VARCHAR2(20 BYTE)               NOT NULL,
  MENU_NM       VARCHAR2(100 BYTE)              NOT NULL,
  MENU_ENG_NM   VARCHAR2(100 BYTE),
  MENU_LEVL     NUMBER(22),
  MENU_PRTS_ID  VARCHAR2(20 BYTE),
  MENU_ORD      NUMBER(22),
  TOP_MENU_YN   CHAR(1 BYTE),
  LEFT_MENU_YN  CHAR(1 BYTE),
  MENU_USE_YN   VARCHAR2(1 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.MENU_MNG IS '메뉴관리';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MENU_ID IS '메뉴 ID';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MENU_NM IS '메뉴 명';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MENU_ENG_NM IS '메뉴 영문 명';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MENU_LEVL IS '메뉴 레벨';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MENU_PRTS_ID IS '상위 메뉴 ID';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MENU_ORD IS '메뉴 순서';

COMMENT ON COLUMN RECRUIT.MENU_MNG.TOP_MENU_YN IS '메뉴 상단 여부';

COMMENT ON COLUMN RECRUIT.MENU_MNG.LEFT_MENU_YN IS '메뉴 왼쪽 여부';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MENU_USE_YN IS '메뉴 사용 여부';

COMMENT ON COLUMN RECRUIT.MENU_MNG.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.MENU_MNG.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.MENU_MNG.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT.MENU_MNG_PK ON RECRUIT.MENU_MNG
(MENU_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.MENU_MNG ADD (
  CONSTRAINT MENU_MNG_PK
 PRIMARY KEY
 (MENU_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

/**
 * 프로그램 : 메뉴 권한
 * 테이블명 : MENU_ROL
 */
DROP TABLE RECRUIT.MENU_ROL CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.MENU_ROL
(
  MENU_ID       VARCHAR2(20 BYTE)               NOT NULL,
  AUTH_GBN      VARCHAR2(20 BYTE)               NOT NULL,
  ROL_ID        VARCHAR2(20 BYTE)               NOT NULL,
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.MENU_ROL IS '메뉴 권한';

COMMENT ON COLUMN RECRUIT.MENU_ROL.MENU_ID IS '메뉴 ID';

COMMENT ON COLUMN RECRUIT.MENU_ROL.AUTH_GBN IS '권한 구분';

COMMENT ON COLUMN RECRUIT.MENU_ROL.ROL_ID IS '권한 ID';

COMMENT ON COLUMN RECRUIT.MENU_ROL.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.MENU_ROL.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.MENU_ROL.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.MENU_ROL.MODIFIY_ID IS '수정자 ID';

/**
 * 프로그램 : 기관 관리
 * 테이블명 : ORG_MNG
 */
ALTER TABLE RECRUIT.ORG_MNG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.ORG_MNG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.ORG_MNG
(
  ORG_CD        VARCHAR2(20 BYTE)               NOT NULL,
  ORG_SMY       CLOB,
  ORG_URL       VARCHAR2(500 BYTE),
  ORG_VCR_URL   VARCHAR2(500 BYTE),
  ORG_IMG_PATH  VARCHAR2(500 BYTE),
  ORG_YEAR      VARCHAR2(4 BYTE),
  ORG_SITE      VARCHAR2(200 BYTE),
  ORG_TEL       VARCHAR2(256 BYTE),
  ORG_TITL      VARCHAR2(1024 BYTE),
  ORG_TITL2     VARCHAR2(1024 BYTE),
  ORG_HR        CLOB,
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (ORG_SMY) STORE AS (
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  INDEX       (
        TABLESPACE USERS
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   ))
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
LOB (ORG_HR) STORE AS (
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  INDEX       (
        TABLESPACE USERS
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   ))
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.ORG_MNG IS '기관관리';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_CD IS '기관 코드';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_SMY IS '기관 개요';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_URL IS '기관 URL';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_VCR_URL IS '기관 홍보영상 URL';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_IMG_PATH IS '기관 이미지 경로';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_YEAR IS '기관 설립연도';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_SITE IS '기관 위치';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_TEL IS '대표 전화';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_TITL IS '기관 개요1';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_TITL2 IS '기관 개요2';

COMMENT ON COLUMN RECRUIT.ORG_MNG.ORG_HR IS '인재상';

COMMENT ON COLUMN RECRUIT.ORG_MNG.CREATE_DTTM IS '생성 일시
';

COMMENT ON COLUMN RECRUIT.ORG_MNG.CREATE_ID IS '생성자 ID

';

COMMENT ON COLUMN RECRUIT.ORG_MNG.MODIFIY_DTTM IS '수정 일시
';

COMMENT ON COLUMN RECRUIT.ORG_MNG.MODIFIY_ID IS '수정자 ID';


ALTER TABLE RECRUIT.ORG_MNG ADD (
  PRIMARY KEY
 (ORG_CD)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

/**
 * 프로그램 : 채용공고 관심분야
 * 테이블명 : RCUIT_CATE_GUBN
 */         
DROP TABLE RECRUIT.RCUIT_CATE_GUBN CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.RCUIT_CATE_GUBN
(
  JOB_SEQ      NUMBER                           NOT NULL,
  ORG_CD       VARCHAR2(20 BYTE),
  GUBN_CODE    VARCHAR2(20 BYTE),
  CREATE_DTTM  DATE
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.RCUIT_CATE_GUBN IS '채용정보 카테고리 구분 테이블';

COMMENT ON COLUMN RECRUIT.RCUIT_CATE_GUBN.JOB_SEQ IS '공고 등록 순번';

COMMENT ON COLUMN RECRUIT.RCUIT_CATE_GUBN.ORG_CD IS '기관 코드';

COMMENT ON COLUMN RECRUIT.RCUIT_CATE_GUBN.GUBN_CODE IS '분류 코드';

COMMENT ON COLUMN RECRUIT.RCUIT_CATE_GUBN.CREATE_DTTM IS '생성 일시
';


CREATE INDEX RECRUIT.RCUIT_CATE_GUBN_IDX ON RECRUIT.RCUIT_CATE_GUBN
(JOB_SEQ, GUBN_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RECRUIT.RCUIT_CATE_IDX ON RECRUIT.RCUIT_CATE_GUBN
(JOB_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RECRUIT.RCUIT_GUBN_IDX ON RECRUIT.RCUIT_CATE_GUBN
(GUBN_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


/**
 * 프로그램 : 채용공고
 * 테이블명 : RCUIT_INFO
 */   
ALTER TABLE RECRUIT.RCUIT_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.RCUIT_INFO CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.RCUIT_INFO
(
  JOB_SEQ          NUMBER                       NOT NULL,
  ORG_CD           VARCHAR2(20 BYTE),
  RCUIT_TITL       VARCHAR2(200 BYTE),
  RCUIT_YN         VARCHAR2(1 BYTE)             DEFAULT 'N',
  RCUIT_STDT       VARCHAR2(100 BYTE),
  RCUIT_EDDT       VARCHAR2(8 BYTE),
  RCUIT_CTTS       CLOB,
  ORG_URL          VARCHAR2(500 BYTE),
  FILE_ATT_GRUPID  VARCHAR2(50 BYTE),
  SEND_YN          VARCHAR2(1 BYTE),
  DEL_YN           VARCHAR2(1 BYTE)             DEFAULT 'N',
  CREATE_DTTM      DATE,
  CREATE_ID        VARCHAR2(512 BYTE),
  MODIFIY_DTTM     DATE,
  MODIFIY_ID       VARCHAR2(512 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (RCUIT_CTTS) STORE AS (
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  INDEX       (
        TABLESPACE SYSTEM
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   ))
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  FREELISTS        1
                  FREELIST GROUPS  1
                  BUFFER_POOL      DEFAULT
                 ))
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.RCUIT_INFO IS '채용정보';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.JOB_SEQ IS '공고 등록 순번';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.ORG_CD IS '기관 코드';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.RCUIT_TITL IS '채용 제목';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.RCUIT_YN IS '채용 여부';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.RCUIT_STDT IS '채용 시작 일자';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.RCUIT_EDDT IS '채용 종료 일자';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.RCUIT_CTTS IS '채용 내용';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.ORG_URL IS '원문 URL';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.FILE_ATT_GRUPID IS '첨부 파일 그룹ID';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.SEND_YN IS 'SMS 발송 여부';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.DEL_YN IS '삭제 여부';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO.MODIFIY_ID IS '수정자 ID';


CREATE INDEX RECRUIT.RCUIT_DT_INFO_IDX ON RECRUIT.RCUIT_INFO
(RCUIT_STDT, RCUIT_EDDT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RECRUIT.RCUIT_INFO_PK ON RECRUIT.RCUIT_INFO
(JOB_SEQ)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RECRUIT.RCUIT_ORGDT_IDX ON RECRUIT.RCUIT_INFO
(ORG_CD, RCUIT_STDT, RCUIT_EDDT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RECRUIT.RCUIT_SEARCH_IDX ON RECRUIT.RCUIT_INFO
(CREATE_DTTM)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.RCUIT_INFO ADD (
  CONSTRAINT RCUIT_INFO_PK
 PRIMARY KEY
 (JOB_SEQ)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

/**
 * 프로그램 : 채용공고 파일
 * 테이블명 : RCUIT_INFO_FILE
 */ 
ALTER TABLE RECRUIT.RCUIT_INFO_FILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.RCUIT_INFO_FILE CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.RCUIT_INFO_FILE
(
  FILE_SN       NUMBER(22)                      NOT NULL,
  JOB_SEQ       NUMBER(22)                      NOT NULL,
  FILE_NM       VARCHAR2(512 BYTE),
  FILE_CONV_NM  VARCHAR2(512 BYTE),
  FILE_SIZE     NUMBER,
  FILE_PATH     VARCHAR2(2000 BYTE),
  DEL_YN        VARCHAR2(1 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.RCUIT_INFO_FILE IS '인재채용 첨부파일 테이블';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.FILE_SN IS '첨부파일 등록 순번';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.JOB_SEQ IS '공고 등록 순번';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.FILE_NM IS '파일 명';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.FILE_CONV_NM IS '첨부파일 변환 명 ';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.FILE_SIZE IS '첨부파일 크기';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.FILE_PATH IS '파일 경로';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.DEL_YN IS '삭제 여부';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.RCUIT_INFO_FILE.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT."XPK채용정보_첨부파일" ON RECRUIT.RCUIT_INFO_FILE
(FILE_SN)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.RCUIT_INFO_FILE ADD (
  CONSTRAINT "XPK채용정보_첨부파일"
 PRIMARY KEY
 (FILE_SN)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

/**
 * 프로그램 : 시스템 로그 관리
 * 테이블명 : SYS_LOG
 */ 
ALTER TABLE RECRUIT.SYS_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.SYS_LOG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.SYS_LOG
(
  SEQ            NUMBER(22)                     NOT NULL,
  LOG_DTTM       DATE,
  USER_ID        VARCHAR2(512 BYTE),
  LOG_IP         VARCHAR2(15 BYTE),
  LOG_ACTN_CONT  VARCHAR2(1000 BYTE),
  VIEW_USER_ID   VARCHAR2(512 BYTE),
  MODIFIY_DTTM   DATE
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RECRUIT.SYS_LOG.SEQ IS '순번';

COMMENT ON COLUMN RECRUIT.SYS_LOG.LOG_DTTM IS '접속 일시';

COMMENT ON COLUMN RECRUIT.SYS_LOG.USER_ID IS '접속 ID';

COMMENT ON COLUMN RECRUIT.SYS_LOG.LOG_IP IS '접속 IP';

COMMENT ON COLUMN RECRUIT.SYS_LOG.LOG_ACTN_CONT IS '접속 행위';

COMMENT ON COLUMN RECRUIT.SYS_LOG.VIEW_USER_ID IS '대상 ID';

COMMENT ON COLUMN RECRUIT.SYS_LOG.MODIFIY_DTTM IS '수정 일시';


CREATE UNIQUE INDEX RECRUIT."XPK시스템_로그" ON RECRUIT.SYS_LOG
(SEQ)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.SYS_LOG ADD (
  CONSTRAINT "XPK시스템_로그"
 PRIMARY KEY
 (SEQ)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

/**
 * 프로그램 : 시스템 모니터링 관리
 * 테이블명 : SYS_MNTR
 */ 
ALTER TABLE RECRUIT.SYS_MNTR
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.SYS_MNTR CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.SYS_MNTR
(
  MNTR_SEQ      NUMBER(22)                      NOT NULL,
  MNTR_DT       VARCHAR2(20 BYTE)               NOT NULL,
  MNTR_GBN      VARCHAR2(20 BYTE),
  MNTR_URL      VARCHAR2(200 BYTE),
  RCRT_CNT      NUMBER(22),
  EML_CNT       NUMBER(22),
  SMS_CNT       NUMBER(22),
  ERR_YN        CHAR(1 BYTE)                    NOT NULL,
  ERR_DESC      CLOB,
  ERR_PRC_YN    CHAR(1 BYTE)                    NOT NULL,
  ERR_PRC_DESC  VARCHAR2(500 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (ERR_DESC) STORE AS (
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  INDEX       (
        TABLESPACE USERS
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   ))
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.SYS_MNTR IS '시스템모니터링';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.CREATE_DTTM IS '생성 일자';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.MODIFIY_ID IS '수정자 ID';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.MNTR_SEQ IS '모니터링 순번';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.MNTR_DT IS '모니터링 일자';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.MNTR_GBN IS '모니터링 구분';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.MNTR_URL IS '호출 URL';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.RCRT_CNT IS '신규 채용 건';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.EML_CNT IS '이메일 발송 건';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.SMS_CNT IS 'SMS 발송 건';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.ERR_YN IS '에러 여부';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.ERR_DESC IS '에러 내용';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.ERR_PRC_YN IS '에러 처리 여부';

COMMENT ON COLUMN RECRUIT.SYS_MNTR.ERR_PRC_DESC IS '에러 처리 내용';


CREATE INDEX RECRUIT.SYS_MNTR_IDX ON RECRUIT.SYS_MNTR
(MNTR_DT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RECRUIT.SYS_MNTR_PK ON RECRUIT.SYS_MNTR
(MNTR_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.SYS_MNTR ADD (
  CONSTRAINT SYS_MNTR_PK
 PRIMARY KEY
 (MNTR_SEQ)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

/**
 * 프로그램 : URL 관리
 * 테이블명 : URL_MNG
 */ 
ALTER TABLE RECRUIT.URL_MNG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.URL_MNG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.URL_MNG
(
  URL_SEQ       NUMBER(22)                      NOT NULL,
  MENU_ID       VARCHAR2(20 BYTE)               NOT NULL,
  AUTH_GBN      VARCHAR2(20 BYTE)               NOT NULL,
  URL           VARCHAR2(200 BYTE)              NOT NULL,
  URL_DESC      VARCHAR2(500 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.URL_MNG IS 'URL관리';

COMMENT ON COLUMN RECRUIT.URL_MNG.URL_SEQ IS 'URL 순번';

COMMENT ON COLUMN RECRUIT.URL_MNG.MENU_ID IS '메뉴 ID';

COMMENT ON COLUMN RECRUIT.URL_MNG.AUTH_GBN IS '권한 구분';

COMMENT ON COLUMN RECRUIT.URL_MNG.URL IS 'URL 경로';

COMMENT ON COLUMN RECRUIT.URL_MNG.URL_DESC IS 'URL 설명';

COMMENT ON COLUMN RECRUIT.URL_MNG.CREATE_DTTM IS '생성 일시
';

COMMENT ON COLUMN RECRUIT.URL_MNG.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.URL_MNG.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.URL_MNG.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT.PK_URL_MNG ON RECRUIT.URL_MNG
(URL_SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX RECRUIT.URL_MNG_IDX ON RECRUIT.URL_MNG
(MENU_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RECRUIT.URL_MNG_PK ON RECRUIT.URL_MNG
(URL_SEQ, MENU_ID, AUTH_GBN, URL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.URL_MNG ADD (
  CONSTRAINT URL_MNG_PK
 PRIMARY KEY
 (URL_SEQ, MENU_ID, AUTH_GBN, URL)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
/**
 * 프로그램 : 사용자 권한 관리
 * 테이블명 : USER_AUTH_MNG
 */ 
DROP TABLE RECRUIT.USER_AUTH_MNG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.USER_AUTH_MNG
(
  USER_ID       VARCHAR2(512 BYTE)              NOT NULL,
  USER_AUTH_CD  VARCHAR2(20 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.USER_AUTH_MNG IS '사용자권한관리';

COMMENT ON COLUMN RECRUIT.USER_AUTH_MNG.USER_ID IS '사용자 ID';

COMMENT ON COLUMN RECRUIT.USER_AUTH_MNG.USER_AUTH_CD IS '사용자 권한';

COMMENT ON COLUMN RECRUIT.USER_AUTH_MNG.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.USER_AUTH_MNG.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.USER_AUTH_MNG.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.USER_AUTH_MNG.MODIFIY_ID IS '수정자 ID';
               
/**
 * 프로그램 : 사용자 관심분야
 * 테이블명 : USER_CLS_MNG
 */ 
ALTER TABLE RECRUIT.USER_CLS_MNG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.USER_CLS_MNG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.USER_CLS_MNG
(
  USER_ID       VARCHAR2(512 BYTE)              NOT NULL,
  CLS_VAL       VARCHAR2(20 BYTE)               NOT NULL,
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.USER_CLS_MNG IS '지원자관심정보';

COMMENT ON COLUMN RECRUIT.USER_CLS_MNG.USER_ID IS '사용자 ID';

COMMENT ON COLUMN RECRUIT.USER_CLS_MNG.CLS_VAL IS '분류 코드';

COMMENT ON COLUMN RECRUIT.USER_CLS_MNG.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.USER_CLS_MNG.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.USER_CLS_MNG.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.USER_CLS_MNG.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT.PK_USER_CLS_MNG ON RECRUIT.USER_CLS_MNG
(USER_ID, CLS_VAL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.USER_CLS_MNG ADD (
  CONSTRAINT USER_CLS_MNG_PK
 PRIMARY KEY
 (USER_ID, CLS_VAL));
               
/**
 * 프로그램 : 사용자 LOG 관리
 * 테이블명 : USER_LOG
 */ 
ALTER TABLE RECRUIT.USER_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.USER_LOG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.USER_LOG
(
  SEQ            NUMBER(22)                     NOT NULL,
  LOG_DTTM       DATE,
  USER_ID        VARCHAR2(512 BYTE),
  LOG_IP         VARCHAR2(15 BYTE)              NOT NULL,
  USER_LOG_CONT  VARCHAR2(1000 BYTE),
  VIEW_USER_ID   VARCHAR2(512 BYTE),
  MDFY_DTTM      DATE
)
TABLESPACE SYSTEM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.USER_LOG IS '사용자로그';

COMMENT ON COLUMN RECRUIT.USER_LOG.SEQ IS '순번';

COMMENT ON COLUMN RECRUIT.USER_LOG.LOG_DTTM IS '회원 정보에 접속한 일시';

COMMENT ON COLUMN RECRUIT.USER_LOG.USER_ID IS '회원 정보에 접속한 ID';

COMMENT ON COLUMN RECRUIT.USER_LOG.LOG_IP IS '회원 정보에 접근한 IP';

COMMENT ON COLUMN RECRUIT.USER_LOG.USER_LOG_CONT IS '회원 정보에 접속하여 실행한 행위';

COMMENT ON COLUMN RECRUIT.USER_LOG.VIEW_USER_ID IS '열람대상 ID';

COMMENT ON COLUMN RECRUIT.USER_LOG.MDFY_DTTM IS '로그인하여 수정한 경우 수정일시';


CREATE UNIQUE INDEX RECRUIT.PK_USER_LOG ON RECRUIT.USER_LOG
(SEQ)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.USER_LOG ADD (
  CONSTRAINT PK_USER_LOG
 PRIMARY KEY
 (SEQ)
    USING INDEX 
    TABLESPACE SYSTEM
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));
               
/**
 * 프로그램 : 사용자 관리
 * 테이블명 : USER_MNG
 */ 
ALTER TABLE RECRUIT.USER_MNG
 DROP PRIMARY KEY CASCADE;

DROP TABLE RECRUIT.USER_MNG CASCADE CONSTRAINTS;

CREATE TABLE RECRUIT.USER_MNG
(
  USER_ID       VARCHAR2(512 BYTE)              NOT NULL,
  USER_SN       VARCHAR2(5 BYTE),
  USER_PWD      VARCHAR2(512 BYTE),
  USER_NM_KOR   VARCHAR2(256 BYTE),
  USER_NM_ENG   VARCHAR2(256 BYTE),
  BRTH_DT       VARCHAR2(8 BYTE),
  SEX_GB        VARCHAR2(2 BYTE),
  TEL1          VARCHAR2(256 BYTE),
  TEL2          VARCHAR2(256 BYTE),
  TEL3          VARCHAR2(256 BYTE),
  CLPN1         VARCHAR2(256 BYTE),
  CLPN2         VARCHAR2(256 BYTE),
  CLPN3         VARCHAR2(256 BYTE),
  ETC_CLPN      VARCHAR2(512 BYTE),
  UNV_BSS_NM    VARCHAR2(512 BYTE),
  PRCSS_CODE    VARCHAR2(2 BYTE),
  MAJOR_NM      VARCHAR2(4000 BYTE),
  PAR_MAJOR_NM  VARCHAR2(4000 BYTE),
  GRADU_DT      VARCHAR2(8 BYTE),
  REP_PAPER     VARCHAR2(4000 BYTE),
  PPR_OUT_RSLT  VARCHAR2(4000 BYTE),
  EML           VARCHAR2(256 BYTE),
  EML_SEND_YN   VARCHAR2(1 BYTE),
  SMS_SEND_YN   VARCHAR2(1 BYTE),
  EXP_DT        VARCHAR2(8 BYTE),
  ORG_CD        VARCHAR2(20 BYTE),
  USE_YN        VARCHAR2(1 BYTE),
  USER_GB       VARCHAR2(2 BYTE),
  CREATE_DTTM   DATE,
  CREATE_ID     VARCHAR2(512 BYTE),
  MODIFIY_DTTM  DATE,
  MODIFIY_ID    VARCHAR2(512 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RECRUIT.USER_MNG IS '사용자 관리';

COMMENT ON COLUMN RECRUIT.USER_MNG.USER_ID IS '사용저 ID';

COMMENT ON COLUMN RECRUIT.USER_MNG.USER_SN IS '사용자 순번';

COMMENT ON COLUMN RECRUIT.USER_MNG.USER_PWD IS '비밀번호';

COMMENT ON COLUMN RECRUIT.USER_MNG.USER_NM_KOR IS '이름 국문';

COMMENT ON COLUMN RECRUIT.USER_MNG.USER_NM_ENG IS '이름 영문';

COMMENT ON COLUMN RECRUIT.USER_MNG.BRTH_DT IS '생년월일';

COMMENT ON COLUMN RECRUIT.USER_MNG.SEX_GB IS '성별구분';

COMMENT ON COLUMN RECRUIT.USER_MNG.TEL1 IS '전화 번호1';

COMMENT ON COLUMN RECRUIT.USER_MNG.TEL2 IS '전화 번호2';

COMMENT ON COLUMN RECRUIT.USER_MNG.TEL3 IS '전화 번호3';

COMMENT ON COLUMN RECRUIT.USER_MNG.CLPN1 IS '핸드폰 번호1';

COMMENT ON COLUMN RECRUIT.USER_MNG.CLPN2 IS '핸드폰 번호2';

COMMENT ON COLUMN RECRUIT.USER_MNG.CLPN3 IS '핸드폰 번호3';

COMMENT ON COLUMN RECRUIT.USER_MNG.UNV_BSS_NM IS '대학(직장)명';

COMMENT ON COLUMN RECRUIT.USER_MNG.PRCSS_CODE IS '과정명';

COMMENT ON COLUMN RECRUIT.USER_MNG.MAJOR_NM IS '전공';

COMMENT ON COLUMN RECRUIT.USER_MNG.PAR_MAJOR_NM IS '세부 전공 분야';

COMMENT ON COLUMN RECRUIT.USER_MNG.GRADU_DT IS '졸업 예정 일자';

COMMENT ON COLUMN RECRUIT.USER_MNG.REP_PAPER IS '대표 논문';

COMMENT ON COLUMN RECRUIT.USER_MNG.PPR_OUT_RSLT IS '논문 외 실적';

COMMENT ON COLUMN RECRUIT.USER_MNG.EML IS '이메일';

COMMENT ON COLUMN RECRUIT.USER_MNG.EML_SEND_YN IS '이메일 수신 여부';

COMMENT ON COLUMN RECRUIT.USER_MNG.SMS_SEND_YN IS 'SMS 수신 여부';

COMMENT ON COLUMN RECRUIT.USER_MNG.EXP_DT IS '만료 일자';

COMMENT ON COLUMN RECRUIT.USER_MNG.ORG_CD IS '기관 코드';

COMMENT ON COLUMN RECRUIT.USER_MNG.USE_YN IS '사용 여부';

COMMENT ON COLUMN RECRUIT.USER_MNG.USER_GB IS '사용자 구분';

COMMENT ON COLUMN RECRUIT.USER_MNG.CREATE_DTTM IS '생성 일시';

COMMENT ON COLUMN RECRUIT.USER_MNG.CREATE_ID IS '생성자 ID';

COMMENT ON COLUMN RECRUIT.USER_MNG.MODIFIY_DTTM IS '수정 일시';

COMMENT ON COLUMN RECRUIT.USER_MNG.MODIFIY_ID IS '수정자 ID';


CREATE UNIQUE INDEX RECRUIT."XPK사용자_관리" ON RECRUIT.USER_MNG
(USER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE RECRUIT.USER_MNG ADD (
  CONSTRAINT USER_MNG_PK
 PRIMARY KEY
 (USER_ID));
               
 

/**
 * 프로그램 : 채용공고 SEQ
 * 시퀀스명 : RCUIT_SEQ
 */        
DROP SEQUENCE RECRUIT.RCUIT_SEQ;

CREATE SEQUENCE RECRUIT.RCUIT_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
  
  