/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-06 08:25:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.faq;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardFAQ_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title></title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"search_section\">\r\n");
      out.write("      <span id=\"spanSelect0\"></span>\r\n");
      out.write("      <input type=\"text\" id=\"inputText\" name=\"\" value=\"\">\r\n");
      out.write("      <input type=\"button\" id=\"searchBtn\" name=\"\" value=\"검색\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"table_section\">\r\n");
      out.write("      <table>\r\n");
      out.write("\r\n");
      out.write("      <colgroup>\r\n");
      out.write("        <col style=\"width:5%\" />\r\n");
      out.write("        <col style=\"width:10%\" />\r\n");
      out.write("        <col style=\"width:35%\">\r\n");
      out.write("        <col style=\"width:20%\">\r\n");
      out.write("        <col style=\"width:10%\">\r\n");
      out.write("        <col style=\"width:10%\">\r\n");
      out.write("      </colgroup>\r\n");
      out.write("      <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>번호</th><th>분류</th><th>제목</th><th>작성자</th><th>등록일</th><th>상태</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("\t\t<tbody id = \"bodyInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("      <div class=\"add_button\">\r\n");
      out.write("        <span id=\"return_page\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  var xmlList;\r\n");
      out.write("  var html=\"\";\r\n");
      out.write("\r\n");
      out.write("// selectBox & button\r\n");
      out.write("var selectBtnList = {\r\n");
      out.write("\tclassification : ['기타','등록관련','임상연구'],\r\n");
      out.write("\tcustomHeader : ['제목','작성자'],\r\n");
      out.write("\tsituation : ['신청완료','답변완료']\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("  var cnt = 0;\r\n");
      out.write("  var selectNm = \"\"\r\n");
      out.write("  var selectBtnId = [];\r\n");
      out.write("  var selectBtnIdstr = \"\";\r\n");
      out.write("  \r\n");
      out.write("for (var p in selectBtnList) {\r\n");
      out.write("\tselectFunC(p,selectBtnList[p]);\r\n");
      out.write("\t \r\n");
      out.write("\t selectBtnId[cnt] = p;\r\n");
      out.write("\t cnt++;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//selectBos 검색 버튼\r\n");
      out.write("$('#searchBtn').click(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar selectClassification = $(\"#\"+selectBtnId[0]+\" option:selected\").text();\r\n");
      out.write("\tvar selectCustomHeader = $(\"#\"+selectBtnId[1]+\" option:selected\").text();\r\n");
      out.write("\tvar selectSituation = $(\"#\"+selectBtnId[2]+\" option:selected\").text();\r\n");
      out.write("\t\r\n");
      out.write("\talert(selectClassification)\r\n");
      out.write("\tvar parameter = {}\r\n");
      out.write("\tparameter.classification = selectClassification;\r\n");
      out.write("\tparameter.customHeader = selectCustomHeader;\r\n");
      out.write("\tparameter.situation = situation;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctxt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/board/faq/boardFAQList.do',\r\n");
      out.write("        type: 'POST',\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\tparam : JSON.stringify(parameter)\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdatatype:'json',\r\n");
      out.write("\t\tcontentType : 'application/json; charset=UTF-8',\r\n");
      out.write("        success: function(data) {  \r\n");
      out.write("        \tconsole.log(data);\r\n");
      out.write("        \t\r\n");
      out.write("        }\r\n");
      out.write("\t})\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function selectFunC(objNm, arr){\r\n");
      out.write("  var add = \"\";\r\n");
      out.write("    add += \"<select id=\"+objNm+\">\";//공통 name으로 하면 선택값 하나만 읽힘\r\n");
      out.write("     for(var i=0 ; i<arr.length ; i++){\r\n");
      out.write("      add += \"<option>\"+arr[i]+\"</option>\";\r\n");
      out.write("    }\r\n");
      out.write("      add += \"</select>\"; \r\n");
      out.write("\r\n");
      out.write("  $('#spanSelect0').append(add); \r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
