/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-01-28 04:24:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title></title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"search_section\">\r\n");
      out.write("      <span id=\"spanSelect0\"></span>\r\n");
      out.write("      <input type=\"text\" id=\"inputText\" name=\"\" value=\"\">\r\n");
      out.write("      <input type=\"button\" id=\"searchBtn\" name=\"\" value=\"검색\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"table_section\">\r\n");
      out.write("      <table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <colgroup>\r\n");
      out.write("        <col style=\"width:5%\" />\r\n");
      out.write("        <col style=\"width:10%\" />\r\n");
      out.write("        <col style=\"width:35%\">\r\n");
      out.write("        <col style=\"width:20%\">\r\n");
      out.write("        <col style=\"width:10%\">\r\n");
      out.write("        <col style=\"width:10%\">\r\n");
      out.write("      </colgroup>\r\n");
      out.write("      <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>번호</th><th>분류</th><th>제목</th><th>작성자</th><th>등록일</th><th>상태</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      <div class=\"add_button\">\r\n");
      out.write("        <span id=\"return_page\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  //tabe 조회\r\n");
      out.write("  $.ajax({\r\n");
      out.write("    url:'/cris/board1/boardList1.do',\r\n");
      out.write("     type:'get',\r\n");
      out.write("    success:function(data){\r\n");
      out.write("\r\n");
      out.write("      for(var i=0; i<data.length;i++){\r\n");
      out.write("        var idx = data[i].idx;\r\n");
      out.write("              $html_string = '<tr>';\r\n");
      out.write("              $html_string += '<td>' + idx + '</td>';\r\n");
      out.write("              $html_string += '<td>' + data[i].title + '</td>';\r\n");
      out.write("              $html_string += '<td>' + data[i].writer + '</td>';\r\n");
      out.write("              $html_string += '<td>' + data[i].creationdate + '</td>';\r\n");
      out.write("              $html_string += '<td>' + data[i].status + '</td>';\r\n");
      out.write("              $html_string += `<td><button class=\"status_approve\" id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">승인</button>`;\r\n");
      out.write("              $html_string += '</tr>';\r\n");
      out.write("              $('table').append($html_string);\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("// html_string += `<td><button class=\"status_approve\" id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(">승인</button>`;\r\n");
      out.write("// <button class=\"add-to-cart\" type=\"button\" onclick=\"openOrderPage(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(")\">구매하기</button>`\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// selectBox & button\r\n");
      out.write("    var classification = ['기타','등록관련','임상연구']\r\n");
      out.write("    var header = ['제목','작성자']\r\n");
      out.write("    var situation = ['신청완료','답변완료']\r\n");
      out.write("//  var situation = [\"등록신청\",\"등록승인\"];  //status 변수명 하면 배열 글자하나씩 나와....-_-+\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var cnt = 0;\r\n");
      out.write("  selectFunC(classification);\r\n");
      out.write("cnt++;\r\n");
      out.write("  selectFunC(header);\r\n");
      out.write("cnt++;\r\n");
      out.write(" selectFunC(situation);\r\n");
      out.write("cnt = 0;\r\n");
      out.write("\r\n");
      out.write("// selectBos 검색 버튼\r\n");
      out.write("$('#searchBtn').click(function(){\r\n");
      out.write("//failed record\r\n");
      out.write("  // alert($(`#addArr0 option:selected`).val());\r\n");
      out.write("// alert($(\"select[name=addArr0]\").val())\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$.ajax({\r\n");
      out.write("  url:'/board_search',\r\n");
      out.write("   type:'get',\r\n");
      out.write("   data:{\r\n");
      out.write("     selected01 : $(\"#addArr0 option:selected\").text(),\r\n");
      out.write("     status : $(\"#addArr1 option:selected\").text(),\r\n");
      out.write("     inputText : $('#inputText').val()\r\n");
      out.write("   },\r\n");
      out.write("  success:function(data){\r\n");
      out.write("    // $('table').remove();\r\n");
      out.write("          // location.reload();\r\n");
      out.write("          // history.back();\r\n");
      out.write("          for(var i=0; i<data.length;i++){\r\n");
      out.write("            var idx = data[i].idx;\r\n");
      out.write("                  $html_string = '<tr>';\r\n");
      out.write("                  $html_string += '<td>' + idx + '</td>';\r\n");
      out.write("                  $html_string += '<td>' + data[i].title + '</td>';\r\n");
      out.write("                  $html_string += '<td>' + data[i].writer + '</td>';\r\n");
      out.write("                  $html_string += '<td>' + data[i].creationdate + '</td>';\r\n");
      out.write("                  $html_string += '<td>' + data[i].status + '</td>';\r\n");
      out.write("                  $html_string += `<td><button class=\"status_approve\" onclick=\"openOrderPage(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(")>승인</button>`;\r\n");
      out.write("                  $html_string += '</tr>';\r\n");
      out.write("                  $('table tbody tr').remove();\r\n");
      out.write("                  $('table').append($html_string);\r\n");
      out.write("          }\r\n");
      out.write("          $html_string ='<td><button id=\"returnList\">목록으로</button></td>';\r\n");
      out.write("            $('#return_page').append($html_string);\r\n");
      out.write("//조회 후 생성된 목록으로 버튼\r\n");
      out.write("            $('#returnList').click(function(){\r\n");
      out.write("              location.href='/'\r\n");
      out.write("            });\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("});//searchBtn end\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// 상태 승인처리 -update with idx\r\n");
      out.write("\r\n");
      out.write("  $(\"status_approve\").click(function(e){\r\n");
      out.write("    var id = e.target.getAttribute('id');\r\n");
      out.write("    alert(id)\r\n");
      out.write("    alert(\"oo?\")\r\n");
      out.write("  // alert($(\".status_approve\").value);\r\n");
      out.write("    // var idx = $(this).attr('id');\r\n");
      out.write("    // var idx = $(this).attr('name');\r\n");
      out.write("    // alert(idx)\r\n");
      out.write("    // $.ajax({\r\n");
      out.write("    //   url:'/status_approve',\r\n");
      out.write("    //    type:'get',\r\n");
      out.write("    //    data:{\r\n");
      out.write("    //      // idx 필요!!\r\n");
      out.write("    //      status : $(\"#addArr1 option:selected\").text(),\r\n");
      out.write("    //    },\r\n");
      out.write("    //   success:function(data){\r\n");
      out.write("    //     alert(\"yo!\")\r\n");
      out.write("    //   }//success end\r\n");
      out.write("    // })\r\n");
      out.write("  });//click end\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function selectFunC( addArr){\r\n");
      out.write("\r\n");
      out.write("  var add = \"\";\r\n");
      out.write("    add += `<select id=\"addArr");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">`;//공통 name으로 하면 선택값 하나만 읽힘\r\n");
      out.write("\r\n");
      out.write("    var searchCategory = `addArr");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("`;\r\n");
      out.write("    for(var i=0; i<addArr.length;i++){\r\n");
      out.write("      add += `<option>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addArr[i]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</option>`;\r\n");
      out.write("    }\r\n");
      out.write("      add += `</select>`;\r\n");
      out.write("\r\n");
      out.write("  // alert($(`#addArr");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" option:selected`).val()); //id\r\n");
      out.write("  // $(`#spanSelect");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("`).append(add);\r\n");
      out.write("  $(`#spanSelect0`).append(add);\r\n");
      out.write("}//function end\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
